#!/usr/bin/env python3
"""Private checked binary64 operations: rational/native and CPU-1/2/JS gates.

The arithmetic oracle and corpus are independent of the candidate. Every
reported observation includes its operation kind.
"""
import random

from binary64_harness import CALCULATE, FIELDS, FRACTION, OBSERVE, controls, kinded, labelled, normal, run
from binary64_ops_oracle import DIV_BOUNDS, KINDS, MUL_BOUNDS, SIGN, checked, inputs, word

CHUNK = 256
SEED = 0x640F5A11


# Fixed IEEE encodings are independent controls, not values generated by either
# rounding path. Quotient ties below are never claimed: finite normal binary64
# division cannot produce a reachable midpoint in this bounded normal domain.
HAND = (
    ('mul', 0x3ff0000000000001, 0x3ff8000000000000, 0x3ff8000000000002, 'hand-product-odd-tie'),
    ('mul', 0x3ff0000000000003, 0x3ff8000000000000, 0x3ff8000000000004, 'hand-product-even-tie'),
    ('mul', 0x3ff0000000000001, 0x3ffffffffffffffe, 0x4000000000000000, 'hand-product-rounding-carry'),
    ('mul', 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 'hand-product-exact'),
    ('div', 0x3ff0000000000000, 0x4008000000000000, 0x3fd5555555555555, 'hand-quotient-repeating'),
    ('div', 0x3ff0000000000001, 0x3ff8000000000000, 0x3fe5555555555557, 'hand-quotient-near-midpoint'),
    ('div', 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 'hand-quotient-exact'),
    ('div', 0x3ff0000000000001, 0x3ff0000000000000, 0x3ff0000000000001, 'hand-quotient-numerator-above'),
    ('div', 0x3ff0000000000000, 0x3ff0000000000001, 0x3feffffffffffffe, 'hand-quotient-numerator-below'),
)


# Reachable quotients lie one half-remainder unit from a midpoint. Each tuple
# gives numerator, denominator, lower neighbor and side (-1 below, +1 above).
# With integer significands M,N these satisfy abs(2*(M*2^52 % N)-N)==1;
# the exact distance to the midpoint is one/(2*N) output ulps, never zero.
NEAR_MIDPOINT = (
    (0x3ff8000000000002, 0x3ff0000000000001, 0x3ff8000000000000, -1),
    (0x3ff8000000000001, 0x3ff0000000000001, 0x3ff7ffffffffffff, 1),
    (0x3ffd55555555555b, 0x3ff0000000000003, 0x3ffd555555555555, -1),
    (0x3ff2aaaaaaaaaaae, 0x3ff0000000000003, 0x3ff2aaaaaaaaaaaa, 1),
)


def samples():
    """Deterministic stratified corpus; deduplicate inputs, retain all labels."""
    rows, record = labelled()
    def add(kind, a, b, label):
        key = (kind, word(a, 64), word(b, 64))
        fields = [part for value in (a, b) for part in (value >> 32, value & 0xffffffff)]
        inputs(kind, *fields)
        record(key, dict(kind=kind, labels=[], **dict(zip(FIELDS, fields))), label)
    def signs(kind, a, b, label, orders=False):
        for sa in (0, SIGN):
            for sb in (0, SIGN):
                add(kind, a ^ sa, b ^ sb, label)
                if orders: add(kind, b ^ sb, a ^ sa, label)
    for kind, a, b, expected, label in HAND:
        result = checked(kind, a >> 32, a & 0xffffffff, b >> 32, b & 0xffffffff)
        if result != (expected >> 32, expected & 0xffffffff):
            raise ValueError('Rational oracle disagrees with fixed hand vector: ' + label)
        signs(kind, a, b, label, kind == 'mul')
        if kind == 'mul':
            for delta in (-1, 1):
                signs(kind, a + delta, b, label + '-left-neighbor', True)
                signs(kind, a, b + delta, label + '-right-neighbor', True)
    for a, b, lower, side in NEAR_MIDPOINT:
        for ea, eb in ((0, 0), (-225, 127), (-149, -149), (127, 127)):
            signs('div', normal(ea, a & FRACTION), normal(eb, b & FRACTION),
                  f'quotient-near-midpoint-side-{side}-lower-parity-{lower % 2}')
    signs('mul', 0, 0, 'all-zero-sign-combinations', True)
    signs('div', 0, 0, 'reject-zero-divisor-including-zero-over-zero')
    for kind, bounds in (('mul', (MUL_BOUNDS, MUL_BOUNDS)), ('div', DIV_BOUNDS)):
        for operand, (low, high) in enumerate(bounds):
            for e in (low, low+1, -1, 0, 1, high-1, high):
                for f in (0, 1, FRACTION):
                    if kind == 'mul': signs(kind, 0, normal(e, f), 'zero-validates-other-before-shortcut', True)
                    else:
                        signs(kind, 0, normal(e, f), 'zero-numerator-and-domain-boundaries')
                        signs(kind, normal(e, f), 0, 'reject-zero-divisor-including-zero-over-zero')
    rng = random.Random(SEED)
    # Every operand exponent and sign participates in accepted arithmetic. The
    # seeded partner is chosen from the independently stated pair constraints.
    for e in range(-554, 128):
        lo, hi = max(-554, -833-e), min(127, 127-e)
        for s in (0, 1):
            f = (0, 1, FRACTION, rng.getrandbits(52))[e % 4]
            a, b = normal(e, f, s), normal(rng.randint(lo, hi), rng.getrandbits(52), rng.getrandbits(1))
            add('mul', a, b, 'every-multiply-exponent-sign-operand-0')
            add('mul', b, a, 'every-multiply-exponent-sign-operand-1')
    for operand, (low, high) in enumerate(DIV_BOUNDS):
        for e in range(low, high+1):
            for s in (0, 1):
                target = normal(e, rng.getrandbits(52), s)
                if operand == 0:
                    a, b = target, normal(rng.randint(max(-149, e), 127), rng.getrandbits(52), rng.getrandbits(1))
                else:
                    a, b = normal(rng.randint(-225, e), rng.getrandbits(52), rng.getrandbits(1)), target
                add('div', a, b, f'every-divide-exponent-sign-operand-{operand}')
    for total in (-834, -833, -832, 126, 127, 128):
        for ea in (-554, -553, -416, -1, 0, 1, 126, 127):
            eb = total-ea
            if -554 <= eb <= 127:
                for fa, fb in ((0, 0), (1, FRACTION), (FRACTION, FRACTION)):
                    signs('mul', normal(ea, fa), normal(eb, fb), f'multiply-pair-exponent-sum-{total}', True)
    for eb in (-149, -148, -1, 0, 1, 126, 127):
        for delta in (-1, 0, 1):
            ea = eb + delta
            if -225 <= ea <= 127:
                for fa, fb in ((0, FRACTION), (0, 0), (FRACTION, 0), (FRACTION, FRACTION)):
                    signs('div', normal(ea, fa), normal(eb, fb), f'divide-pair-exponent-difference-{delta}')
    # Product midpoint parity/carry, sticky-tail and each 32-bit limb boundary.
    for e in (-554, -553, -416, -1, 0, 1, 126, 127):
        partner = max(-554, min(0, -833-e))
        for bit in range(52):
            for f in (1 << bit, FRACTION ^ (1 << bit)):
                signs('mul', normal(e, f), normal(partner, FRACTION), f'product-significand-bit-{bit}', True)
    for e in (-416, -1, 0, 63, 127):
        for f in (0, 1, 2, 3, 0xffffffff, 0x100000000, 0x100000001, FRACTION-2, FRACTION-1, FRACTION):
            for g in (1, 1 << 51, FRACTION-1, FRACTION):
                signs('mul', normal(e, f), normal(min(0, 127-e), g), 'product-ties-sticky-limb-carries', True)
    # Division a<b, a=b and a>b normalized significands; odd denominators give
    # repeating/long remainders, and powers of two give independently exact cases.
    for bit in range(52):
        for f in (1 << bit, FRACTION ^ (1 << bit)):
            for g in (0, 1, FRACTION):
                signs('div', normal(0, f), normal(0, g), f'quotient-significand-bit-{bit}')
    for e in (-225, -224, -149, -1, 0, 1, 126, 127):
        eb = max(e, -149)
        for f in (0, 1, 2, 3, 0xffffffff, 0x100000000, 0x100000001, FRACTION-2, FRACTION-1, FRACTION):
            for g in (0, 1, 2, 3, (1 << 51)-1, 1 << 51, (1 << 51)+1, FRACTION):
                signs('div', normal(e, f), normal(eb, g), 'quotient-exact-repeating-long-remainders-near-midpoints')
    for gap in (0, 1, 2, 31, 32, 33, 51, 52, 53, 63, 64, 65, 127, 128, 149, 224, 225, 351, 352):
        ea, eb = 127-gap, 127
        for fa, fb in ((0, 0), (1, FRACTION), (FRACTION, 1), (FRACTION, FRACTION)):
            signs('div', normal(ea, fa), normal(eb, fb), f'quotient-exponent-gap-{gap}')
    for kind, bounds in (('mul', (MUL_BOUNDS, MUL_BOUNDS)), ('div', DIV_BOUNDS)):
        for operand, (low, high) in enumerate(bounds):
            invalid = [normal(e, f, s) for e in (-1022, low-1, high+1, 1023)
                       for f in (0, 1, FRACTION) for s in (0, 1)]
            invalid += [s | f for s in (0, SIGN) for f in (1, 1<<31, 1<<32, 1<<51, FRACTION)]
            invalid += [s | (2047<<52) | f for s in (0, SIGN) for f in (0, 1, 1<<32, 1<<51, FRACTION)]
            for bad in invalid:
                for other in (0, SIGN, normal(0), normal(-1, FRACTION, 1)):
                    a, b = (bad, other) if operand == 0 else (other, bad)
                    add(kind, a, b, f'reject-invalid-{kind}-operand-{operand}')
    # All stored normal exponents/signs, including those outside arithmetic
    # domains. Identity exercises checked_decode + canonical encode directly.
    for e in range(-1022, 1024):
        for s in (0, 1):
            f = (0, 1, FRACTION, rng.getrandbits(52))[e % 4]
            for kind in ('identity', 'finite'):
                add(kind, normal(e, f, s), 0, 'all-binary64-normal-exponents-and-signs')
    special = (0, 1, 2, (1<<31)-1, 1<<31, 1<<32, (1<<51)-1, 1<<51, FRACTION,
               1<<52, (1<<52)+1, 0x7fefffffffffffff, 0x7ff0000000000000,
               0x7ff0000000000001, 0x7ff8000000000000, 0x7fffffffffffffff)
    for value in special:
        for s in (0, SIGN):
            for kind in ('identity', 'finite'):
                add(kind, value | s, 0, 'adapter-zero-subnormal-transition-nonfinite')
    # Promotion is checked directly against exact rationals and native casts,
    # including every exponent/sign and each subnormal leading-bit transition.
    for e in range(255):
        for s in (0, 1):
            for f in (0, 1, (1<<23)-1, rng.getrandbits(23)):
                add('promote', (s<<31) | (e<<23) | f, 0, 'all-finite-binary32-exponents-and-signs')
    for bit in range(23):
        for delta in (-1, 0, 1):
            for s in (0, 1):
                add('promote', (s<<31) | ((1<<bit)+delta), 0, f'promotion-subnormal-leading-bit-{bit}')
    for e in (0, 1, 2, 126, 127, 128, 253, 254):
        for bit in range(23):
            for f in (1<<bit, ((1<<23)-1) ^ (1<<bit)):
                for s in (0, 1):
                    add('promote', (s<<31) | (e<<23) | f, 0, f'promotion-fraction-bit-{bit}')
    for value in (0, 1, (1<<22)-1, 1<<22, (1<<23)-1):
        for s in (0, 1):
            add('promote', (s<<31) | (255<<23) | value, 0, 'reject-binary32-nonfinite')
    # Raw word helpers use unsigned modular encodings, including sign crossings
    # and specials. They make no claim about arithmetic on those special values.
    words = {0, 1, 2, SIGN-1, SIGN, SIGN+1, (1<<64)-2, (1<<64)-1, *special}
    for bit in range(64):
        for delta in (-1, 0, 1):
            words.add(((1<<bit)+delta) & ((1<<64)-1))
    words |= {value ^ SIGN for value in words.copy()}
    for a in sorted(words):
        for kind in ('negate', 'increment', 'decrement'):
            add(kind, a, 0, 'raw-word-all-bit-carry-borrow-boundaries')
        for b in (a, a^SIGN, (a+1)&((1<<64)-1), 0, SIGN):
            for kind in ('magnitude', 'equal'):
                add(kind, a, b, 'raw-magnitude-and-finite-numerical-equality')
    for e in range(1, 2047):
        add('power', e, 0, 'all-2046-normal-power-exponents')
    for e in (0, 2047, 2048, 0x7fffffff, 0x80000000, 0xffffffff):
        add('power', e, 0, 'reject-power-exponent-outside-stored-normal-range')
    for index, row in enumerate(rows): row['id'] = index
    return rows


EXPRESSIONS = {
    'mul': 'O.checked_multiply(ah, al, bh, bl)',
    'div': 'O.checked_divide(ah, al, bh, bl)',
    'identity': 'O.checked_identity(ah, al)',
    'promote': 'O.checked_promote(al)',
    'finite': 'O.checked_finite(ah, al)',
    'negate': 'Some{O.negate(ah, al)}',
    'magnitude': 'Some{F.Words{0, O.magnitude_order(ah, al, bh, bl)}}',
    'equal': 'Some{F.Words{0, Bool.to_u32(O.numerical_equal(ah, al, bh, bl))}}',
    'increment': 'Some{O.increment(ah, al)}',
    'decrement': 'Some{O.decrement(ah, al)}',
    'power': 'O.checked_power(al)',
}
expected_row, task, native_input = kinded(KINDS, checked)
PROGRAM = ('''import Base
import ../../src/binary64_fma.bend as F
import ../../src/binary64_ops.bend as O
type Task is Data:
''' + ''.join(f'  {kind.title()}{{index: U32, ah: U32, al: U32, bh: U32, bl: U32}}\n' for kind in KINDS)
           + OBSERVE + '''def one(task: Task, rest: List<U32>) -> List<U32>:
  match task:
''' + ''.join(f'    case {kind.title()}{{index, ah, al, bh, bl}}: observe(index, {number}, {EXPRESSIONS[kind]}, rest)\n'
             for kind, number in KINDS.items()) + CALCULATE)


# Native controls intentionally exceed candidate arithmetic domains. The
# subnormal controls detect FTZ/DAZ at runtime rather than trusting compiler flags.
# kind 3 means a direct binary32-to-binary64 cast; its input is in the low word.
NATIVE_CONTROLS = (
    (0, 0x3ff0000000000001, 0x3ff8000000000000, 0x3ff8000000000002),
    (0, 0x3ff0000000000003, 0x3ff8000000000000, 0x3ff8000000000004),
    (0, 0x3ff0000000000001, 0x3ffffffffffffffe, 0x4000000000000000),
    (0, 0xbff0000000000001, 0x3ff8000000000000, 0xbff8000000000002),
    (1, 0x3ff0000000000000, 0x4008000000000000, 0x3fd5555555555555),
    (1, 0xbff0000000000000, 0x4008000000000000, 0xbfd5555555555555),
    (1, 0x3ff0000000000001, 0x3ff8000000000000, 0x3fe5555555555557),
    (1, 0x3ff0000000000000, 0x3ff0000000000001, 0x3feffffffffffffe),
    (0, 0x0000000000000000, 0x3ff0000000000000, 0x0000000000000000),
    (0, 0x0000000000000000, 0xbff0000000000000, 0x8000000000000000),
    (0, 0x8000000000000000, 0x3ff0000000000000, 0x8000000000000000),
    (0, 0x8000000000000000, 0xbff0000000000000, 0x0000000000000000),
    (1, 0x0000000000000000, 0x3ff0000000000000, 0x0000000000000000),
    (1, 0x0000000000000000, 0xbff0000000000000, 0x8000000000000000),
    (1, 0x8000000000000000, 0x3ff0000000000000, 0x8000000000000000),
    (1, 0x8000000000000000, 0xbff0000000000000, 0x0000000000000000),
    (0, 0x0000000000000001, 0x3ff0000000000000, 0x0000000000000001),
    (0, 0x8000000000000001, 0x3ff0000000000000, 0x8000000000000001),
    (0, 0x0010000000000000, 0x3fe0000000000000, 0x0008000000000000),
    (0, 0x000fffffffffffff, 0x4000000000000000, 0x001ffffffffffffe),
    (1, 0x0000000000000001, 0x3ff0000000000000, 0x0000000000000001),
    (1, 0x0010000000000000, 0x4000000000000000, 0x0008000000000000),
    (1, 0x8000000000000002, 0x4000000000000000, 0x8000000000000001),
    (1, 0x0010000000000000, 0x3ff0000000000001, 0x000fffffffffffff),
    (3, 0x00000000, 0, 0x0000000000000000),
    (3, 0x80000000, 0, 0x8000000000000000),
    (3, 0x00000001, 0, 0x36a0000000000000),
    (3, 0x80000001, 0, 0xb6a0000000000000),
    (3, 0x007fffff, 0, 0x380fffffc0000000),
    (3, 0x00800000, 0, 0x3810000000000000),
    (3, 0x3f800001, 0, 0x3ff0000020000000),
    (3, 0x7f7fffff, 0, 0x47efffffe0000000),
)
NATIVE = r'''#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <float.h>
#include <limits.h>
#include <fenv.h>
#include <inttypes.h>
#if defined(__x86_64__) || defined(__i386__)
#include <xmmintrin.h>
#elif !defined(__aarch64__)
#error Unsupported floating point control-register qualification
#endif
#ifdef __FAST_MATH__
#error Fast math invalidates this oracle
#endif
#pragma STDC FENV_ACCESS ON
#pragma STDC FP_CONTRACT OFF
_Static_assert(CHAR_BIT == 8 && sizeof(double) == 8 && sizeof(float) == 4, "word layout");
_Static_assert(FLT_RADIX == 2 && DBL_MANT_DIG == 53 && DBL_MIN_EXP == -1021 && DBL_MAX_EXP == 1024, "binary64");
_Static_assert(FLT_MANT_DIG == 24 && FLT_MIN_EXP == -125 && FLT_MAX_EXP == 128, "binary32");
_Static_assert(FLT_EVAL_METHOD == 0, "binary64 evaluation without excess precision");
static double mul_values(double a, double b) {
  volatile double va=a, vb=b; volatile double result=va*vb; return result;
}
static double div_values(double a, double b) {
  volatile double va=a, vb=b; volatile double result=va/vb; return result;
}
static double promote_value(float a) {
  volatile float va=a; volatile double result=(double)va; return result;
}
static double (* volatile runtime_mul)(double, double) = mul_values;
static double (* volatile runtime_div)(double, double) = div_values;
static double (* volatile runtime_promote)(float) = promote_value;
static uint64_t evaluate(unsigned kind, uint64_t a, uint64_t b) {
  double da,db,result; uint64_t bits;
  if (kind == 3) {
    uint32_t low=(uint32_t)a; float input; memcpy(&input,&low,4);
    volatile double computed=runtime_promote(input); result=computed;
  } else {
    memcpy(&da,&a,8); memcpy(&db,&b,8);
    volatile double computed=kind ? runtime_div(da,db) : runtime_mul(da,db); result=computed;
  }
  memcpy(&bits,&result,8); return bits;
}
static int expof(uint64_t a) { return (int)((a>>52)&2047)-1023; }
static uint64_t magnitude(uint64_t a) { return a & UINT64_C(0x7fffffffffffffff); }
static int finite_bits(uint64_t a) { return ((a>>52)&2047) != 2047; }
static int normal_or_zero(uint64_t a, int lo, int hi) {
  if (!magnitude(a)) return 1;
  unsigned e=(unsigned)((a>>52)&2047);
  return e && e != 2047 && expof(a) >= lo && expof(a) <= hi;
}
static int operation(unsigned kind, uint64_t a, uint64_t b, uint64_t *out) {
  switch (kind) {
  case 0:
    if (!normal_or_zero(a,-554,127) || !normal_or_zero(b,-554,127)) return 0;
    if (magnitude(a) && magnitude(b) && (expof(a)+expof(b)<-833 || expof(a)+expof(b)>127)) return 0;
    *out=evaluate(kind,a,b); return 1;
  case 1:
    if (!normal_or_zero(a,-225,127) || !normal_or_zero(b,-149,127) || !magnitude(b)) return 0;
    if (magnitude(a) && expof(a)>expof(b)) return 0;
    *out=evaluate(kind,a,b); return 1;
  case 2:
    if (!normal_or_zero(a,-1022,1023)) return 0;
    *out=a; return 1;
  case 3:
    if (((a>>23)&255) == 255) return 0;
    *out=evaluate(kind,a,b); return 1;
  case 4:
    if (!finite_bits(a)) return 0;
    *out=a; return 1;
  case 5: *out=a^UINT64_C(0x8000000000000000); return 1;
  case 6: *out=magnitude(a)==magnitude(b) ? 0 : magnitude(a)<magnitude(b) ? 1 : 2; return 1;
  case 7:
    if (!finite_bits(a) || !finite_bits(b)) { *out=0; return 1; }
    double da,db; memcpy(&da,&a,8); memcpy(&db,&b,8); *out=(da==db); return 1;
  case 8: *out=a+UINT64_C(1); return 1;
  case 9: *out=a-UINT64_C(1); return 1;
  case 10:
    if (a<1 || a>2046) return 0;
    *out=a<<52; return 1;
  }
  return -1;
}
int main(void) {
  int initial=fegetround();
  if (initial < 0 || fesetround(FE_TONEAREST) || fegetround() != FE_TONEAREST) return 2;
  uint64_t control; const char *control_name;
#if defined(__x86_64__) || defined(__i386__)
  control=_mm_getcsr(); control_name="mxcsr";
  if (control & ((1u<<15) | (1u<<6) | (3u<<13))) return 3;
#else
  __asm__ volatile("mrs %0, fpcr" : "=r"(control)); control_name="fpcr";
  if (control & ((1ull<<24) | (1ull<<19) | (3ull<<22) | 3ull)) return 3;
#endif
  double one=1.0; uint64_t one_bits; memcpy(&one_bits,&one,8);
  float fone=1.0f; uint32_t fone_bits; memcpy(&fone_bits,&fone,4);
  if (one_bits != UINT64_C(0x3ff0000000000000) || fone_bits != UINT32_C(0x3f800000)) return 4;
  static const uint64_t controls[][4] = {
@CONTROLS@
  };
  unsigned preflights=(unsigned)(sizeof controls/sizeof controls[0]);
  for (unsigned i=0;i<preflights;i++) {
    if (evaluate((unsigned)controls[i][0],controls[i][1],controls[i][2]) != controls[i][3]) {
      fprintf(stderr,"Runtime mul/div/promote preflight %u failed\n",i); return 7;
    }
  }
  printf("{\"rounding\":\"FE_TONEAREST\",\"initial_rounding\":%d,\"selected_rounding\":%d,\"control_name\":\"%s\",\"control\":%" PRIu64 ",\"ftz\":false,\"daz\":false,\"runtime_mul\":true,\"runtime_div\":true,\"runtime_promote\":true,\"binary64_evaluation\":true,\"preflight_count\":%u,\"char_bit\":%d,\"double_bytes\":%zu,\"float_bytes\":%zu,\"double_mantissa\":%d,\"float_mantissa\":%d,\"float_eval_method\":%d,\"one_bits\":\"%016" PRIx64 "\"}\n",initial,fegetround(),control_name,control,preflights,CHAR_BIT,sizeof(double),sizeof(float),DBL_MANT_DIG,FLT_MANT_DIG,FLT_EVAL_METHOD,one_bits);
  FILE *in=fopen(INPUT,"r"); if (!in) return 5;
  uint32_t index,kind,ah,al,bh,bl; int count;
  while ((count=fscanf(in,"%" SCNu32 " %" SCNu32 " %" SCNu32 " %" SCNu32 " %" SCNu32 " %" SCNu32,&index,&kind,&ah,&al,&bh,&bl)) == 6) {
    if (kind>10 || ((kind!=0 && kind!=1 && kind!=6 && kind!=7) && (bh || bl)) || ((kind==3 || kind==10) && ah)) { fclose(in); return 8; }
    uint64_t a=((uint64_t)ah<<32)|al,b=((uint64_t)bh<<32)|bl,bits=0;
    int accepted=operation(kind,a,b,&bits);
    if (accepted<0) { fclose(in); return 8; }
    printf("[%" PRIu32 ",%" PRIu32 ",%d,%" PRIu32 ",%" PRIu32 "]\n",index,kind,accepted,(uint32_t)(bits>>32),(uint32_t)bits);
  }
  if (count != EOF || ferror(in) || fclose(in)) return 6;
  return 0;
}
'''.replace('@CONTROLS@', controls(NATIVE_CONTROLS))


def main():
    run('binary64-ops', __doc__, rows=samples(), expected_row=expected_row, native=NATIVE,
        native_rows=lambda row: True, native_input=native_input,
        metadata=('rounding', 'initial_rounding', 'selected_rounding', 'control_name', 'control', 'ftz', 'daz',
                  'runtime_mul', 'runtime_div', 'runtime_promote', 'binary64_evaluation', 'preflight_count',
                  'char_bit', 'double_bytes', 'float_bytes', 'double_mantissa', 'float_mantissa',
                  'float_eval_method', 'one_bits'),
        layout=dict(char_bit=8, double_bytes=8, float_bytes=4, double_mantissa=53, float_mantissa=24,
                    float_eval_method=0, one_bits='3ff0000000000000'),
        header=PROGRAM, task=task, width=5, batch=CHUNK, preflights=len(NATIVE_CONTROLS))


if __name__ == '__main__':
    main()
