#!/usr/bin/env python3
"""Private checked binary64 operations: rational/native and CPU-1/2/JS gates.

Subprocess retention, fresh compilation and drift checks follow the existing
private FMA harness. The arithmetic oracle and corpus are independent of the
candidate. Every reported observation includes its operation kind.
"""
import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import platform
import random
import re
import shutil
import subprocess
import time

from binary64_ops_oracle import (FRACTION, KINDS, SIGN, checked, decode32,
                                decode64, in_domain, nearest64, power2, word,
                                allowed, inputs, MUL_BOUNDS, MUL_SUM_BOUNDS, DIV_BOUNDS)
from conformance import BUILD, ROOT, checkout, source_gate

CHUNK = 256
LINE = 16
WIDTH = 5
SEED = 0x640F5A11
FIELDS = ('ah', 'al', 'bh', 'bl')
FLAGS = ['-std=c11', '-O2', '-frounding-math', '-fno-fast-math',
         '-ffp-contract=off', '-fno-lto']
DEPENDENCIES = ('src/binary64_ops.bend', 'src/float64.bend', 'src/float64_ops.bend', 'src/binary64_fma.bend',
                'tools/binary64_ops_probe.py', 'tools/binary64_ops_oracle.py',
                'tools/binary64_fma_oracle.py', 'tests/test_binary64_ops.py',
                'tools/conformance.py', 'LAWS.bend', 'PROOF.bend', 'toolchain.json')


def normal(exponent, fraction=0, sign=0):
    if (type(exponent) is not int or type(fraction) is not int or type(sign) is not int
            or not -1022 <= exponent <= 1023 or not 0 <= fraction <= FRACTION or sign not in (0, 1)):
        raise ValueError('Invalid normal binary64 parameters')
    return (sign << 63) | ((exponent + 1023) << 52) | fraction


# Fixed IEEE encodings are independent controls, not values generated by either
# rounding path. Quotient ties below are never claimed: finite normal binary64
# division cannot produce a reachable midpoint in this bounded normal domain.
HAND = (
    ('mul', 0x3ff0000000000001, 0x3ff8000000000000, 0x3ff8000000000002, 'hand-product-odd-tie'),
    ('mul', 0x3ff0000000000003, 0x3ff8000000000000, 0x3ff8000000000004, 'hand-product-even-tie'),
    ('mul', 0x3ff0000000000001, 0x3ffffffffffffffe, 0x4000000000000000, 'hand-product-rounding-carry'),
    ('mul', 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 'hand-product-exact'),
    ('div', 0x3ff0000000000000, 0x4008000000000000, 0x3fd5555555555555, 'hand-quotient-repeating'),
    ('div', 0x3ff0000000000001, 0x3ff8000000000000, 0x3fe5555555555557, 'hand-quotient-near-midpoint'),
    ('div', 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 'hand-quotient-exact'),
    ('div', 0x3ff0000000000001, 0x3ff0000000000000, 0x3ff0000000000001, 'hand-quotient-numerator-above'),
    ('div', 0x3ff0000000000000, 0x3ff0000000000001, 0x3feffffffffffffe, 'hand-quotient-numerator-below'),
)


# Reachable quotients lie one half-remainder unit from a midpoint. Each tuple
# gives numerator, denominator, lower neighbor and side (-1 below, +1 above).
# With integer significands M,N these satisfy abs(2*(M*2^52 % N)-N)==1;
# the exact distance to the midpoint is one/(2*N) output ulps, never zero.
NEAR_MIDPOINT = (
    (0x3ff8000000000002, 0x3ff0000000000001, 0x3ff8000000000000, -1),
    (0x3ff8000000000001, 0x3ff0000000000001, 0x3ff7ffffffffffff, 1),
    (0x3ffd55555555555b, 0x3ff0000000000003, 0x3ffd555555555555, -1),
    (0x3ff2aaaaaaaaaaae, 0x3ff0000000000003, 0x3ff2aaaaaaaaaaaa, 1),
)


def samples():
    """Deterministic stratified corpus; deduplicate inputs, retain all labels."""
    rows, seen = [], {}
    def add(kind, a, b, label):
        key = (kind, word(a, 64), word(b, 64))
        fields = [part for value in (a, b) for part in (value >> 32, value & 0xffffffff)]
        inputs(kind, *fields)
        if key not in seen:
            row = dict(kind=kind, labels=[])
            row.update(zip(FIELDS, fields))
            rows.append(row); seen[key] = row
        if label not in seen[key]['labels']:
            seen[key]['labels'].append(label)
    def signs(kind, a, b, label, orders=False):
        for sa in (0, SIGN):
            for sb in (0, SIGN):
                add(kind, a ^ sa, b ^ sb, label)
                if orders: add(kind, b ^ sb, a ^ sa, label)
    for kind, a, b, expected, label in HAND:
        result = checked(kind, a >> 32, a & 0xffffffff, b >> 32, b & 0xffffffff)
        if result != (expected >> 32, expected & 0xffffffff):
            raise ValueError('Rational oracle disagrees with fixed hand vector: ' + label)
        signs(kind, a, b, label, kind == 'mul')
        if kind == 'mul':
            for delta in (-1, 1):
                signs(kind, a + delta, b, label + '-left-neighbor', True)
                signs(kind, a, b + delta, label + '-right-neighbor', True)
    for a, b, lower, side in NEAR_MIDPOINT:
        for ea, eb in ((0, 0), (-225, 127), (-149, -149), (127, 127)):
            signs('div', normal(ea, a & FRACTION), normal(eb, b & FRACTION),
                  f'quotient-near-midpoint-side-{side}-lower-parity-{lower % 2}')
    signs('mul', 0, 0, 'all-zero-sign-combinations', True)
    signs('div', 0, 0, 'reject-zero-divisor-including-zero-over-zero')
    for kind, bounds in (('mul', (MUL_BOUNDS, MUL_BOUNDS)), ('div', DIV_BOUNDS)):
        for operand, (low, high) in enumerate(bounds):
            for e in (low, low+1, -1, 0, 1, high-1, high):
                for f in (0, 1, FRACTION):
                    if kind == 'mul': signs(kind, 0, normal(e, f), 'zero-validates-other-before-shortcut', True)
                    else:
                        signs(kind, 0, normal(e, f), 'zero-numerator-and-domain-boundaries')
                        signs(kind, normal(e, f), 0, 'reject-zero-divisor-including-zero-over-zero')
    rng = random.Random(SEED)
    # Every operand exponent and sign participates in accepted arithmetic. The
    # seeded partner is chosen from the independently stated pair constraints.
    for e in range(-554, 128):
        lo, hi = max(-554, -833-e), min(127, 127-e)
        for s in (0, 1):
            f = (0, 1, FRACTION, rng.getrandbits(52))[e % 4]
            a, b = normal(e, f, s), normal(rng.randint(lo, hi), rng.getrandbits(52), rng.getrandbits(1))
            add('mul', a, b, 'every-multiply-exponent-sign-operand-0')
            add('mul', b, a, 'every-multiply-exponent-sign-operand-1')
    for operand, (low, high) in enumerate(DIV_BOUNDS):
        for e in range(low, high+1):
            for s in (0, 1):
                target = normal(e, rng.getrandbits(52), s)
                if operand == 0:
                    a, b = target, normal(rng.randint(max(-149, e), 127), rng.getrandbits(52), rng.getrandbits(1))
                else:
                    a, b = normal(rng.randint(-225, e), rng.getrandbits(52), rng.getrandbits(1)), target
                add('div', a, b, f'every-divide-exponent-sign-operand-{operand}')
    for total in (-834, -833, -832, 126, 127, 128):
        for ea in (-554, -553, -416, -1, 0, 1, 126, 127):
            eb = total-ea
            if -554 <= eb <= 127:
                for fa, fb in ((0, 0), (1, FRACTION), (FRACTION, FRACTION)):
                    signs('mul', normal(ea, fa), normal(eb, fb), f'multiply-pair-exponent-sum-{total}', True)
    for eb in (-149, -148, -1, 0, 1, 126, 127):
        for delta in (-1, 0, 1):
            ea = eb + delta
            if -225 <= ea <= 127:
                for fa, fb in ((0, FRACTION), (0, 0), (FRACTION, 0), (FRACTION, FRACTION)):
                    signs('div', normal(ea, fa), normal(eb, fb), f'divide-pair-exponent-difference-{delta}')
    # Product midpoint parity/carry, sticky-tail and each 32-bit limb boundary.
    for e in (-554, -553, -416, -1, 0, 1, 126, 127):
        partner = max(-554, min(0, -833-e))
        for bit in range(52):
            for f in (1 << bit, FRACTION ^ (1 << bit)):
                signs('mul', normal(e, f), normal(partner, FRACTION), f'product-significand-bit-{bit}', True)
    for e in (-416, -1, 0, 63, 127):
        for f in (0, 1, 2, 3, 0xffffffff, 0x100000000, 0x100000001, FRACTION-2, FRACTION-1, FRACTION):
            for g in (1, 1 << 51, FRACTION-1, FRACTION):
                signs('mul', normal(e, f), normal(min(0, 127-e), g), 'product-ties-sticky-limb-carries', True)
    # Division a<b, a=b and a>b normalized significands; odd denominators give
    # repeating/long remainders, and powers of two give independently exact cases.
    for bit in range(52):
        for f in (1 << bit, FRACTION ^ (1 << bit)):
            for g in (0, 1, FRACTION):
                signs('div', normal(0, f), normal(0, g), f'quotient-significand-bit-{bit}')
    for e in (-225, -224, -149, -1, 0, 1, 126, 127):
        eb = max(e, -149)
        for f in (0, 1, 2, 3, 0xffffffff, 0x100000000, 0x100000001, FRACTION-2, FRACTION-1, FRACTION):
            for g in (0, 1, 2, 3, (1 << 51)-1, 1 << 51, (1 << 51)+1, FRACTION):
                signs('div', normal(e, f), normal(eb, g), 'quotient-exact-repeating-long-remainders-near-midpoints')
    for gap in (0, 1, 2, 31, 32, 33, 51, 52, 53, 63, 64, 65, 127, 128, 149, 224, 225, 351, 352):
        ea, eb = 127-gap, 127
        for fa, fb in ((0, 0), (1, FRACTION), (FRACTION, 1), (FRACTION, FRACTION)):
            signs('div', normal(ea, fa), normal(eb, fb), f'quotient-exponent-gap-{gap}')
    for kind, bounds in (('mul', (MUL_BOUNDS, MUL_BOUNDS)), ('div', DIV_BOUNDS)):
        for operand, (low, high) in enumerate(bounds):
            invalid = [normal(e, f, s) for e in (-1022, low-1, high+1, 1023)
                       for f in (0, 1, FRACTION) for s in (0, 1)]
            invalid += [s | f for s in (0, SIGN) for f in (1, 1<<31, 1<<32, 1<<51, FRACTION)]
            invalid += [s | (2047<<52) | f for s in (0, SIGN) for f in (0, 1, 1<<32, 1<<51, FRACTION)]
            for bad in invalid:
                for other in (0, SIGN, normal(0), normal(-1, FRACTION, 1)):
                    a, b = (bad, other) if operand == 0 else (other, bad)
                    add(kind, a, b, f'reject-invalid-{kind}-operand-{operand}')
    # All stored normal exponents/signs, including those outside arithmetic
    # domains. Identity exercises checked_decode + canonical encode directly.
    for e in range(-1022, 1024):
        for s in (0, 1):
            f = (0, 1, FRACTION, rng.getrandbits(52))[e % 4]
            for kind in ('identity', 'finite'):
                add(kind, normal(e, f, s), 0, 'all-binary64-normal-exponents-and-signs')
    special = (0, 1, 2, (1<<31)-1, 1<<31, 1<<32, (1<<51)-1, 1<<51, FRACTION,
               1<<52, (1<<52)+1, 0x7fefffffffffffff, 0x7ff0000000000000,
               0x7ff0000000000001, 0x7ff8000000000000, 0x7fffffffffffffff)
    for value in special:
        for s in (0, SIGN):
            for kind in ('identity', 'finite'):
                add(kind, value | s, 0, 'adapter-zero-subnormal-transition-nonfinite')
    # Promotion is checked directly against exact rationals and native casts,
    # including every exponent/sign and each subnormal leading-bit transition.
    for e in range(255):
        for s in (0, 1):
            for f in (0, 1, (1<<23)-1, rng.getrandbits(23)):
                add('promote', (s<<31) | (e<<23) | f, 0, 'all-finite-binary32-exponents-and-signs')
    for bit in range(23):
        for delta in (-1, 0, 1):
            for s in (0, 1):
                add('promote', (s<<31) | ((1<<bit)+delta), 0, f'promotion-subnormal-leading-bit-{bit}')
    for e in (0, 1, 2, 126, 127, 128, 253, 254):
        for bit in range(23):
            for f in (1<<bit, ((1<<23)-1) ^ (1<<bit)):
                for s in (0, 1):
                    add('promote', (s<<31) | (e<<23) | f, 0, f'promotion-fraction-bit-{bit}')
    for value in (0, 1, (1<<22)-1, 1<<22, (1<<23)-1):
        for s in (0, 1):
            add('promote', (s<<31) | (255<<23) | value, 0, 'reject-binary32-nonfinite')
    # Raw word helpers use unsigned modular encodings, including sign crossings
    # and specials. They make no claim about arithmetic on those special values.
    words = {0, 1, 2, SIGN-1, SIGN, SIGN+1, (1<<64)-2, (1<<64)-1, *special}
    for bit in range(64):
        for delta in (-1, 0, 1):
            words.add(((1<<bit)+delta) & ((1<<64)-1))
    words |= {value ^ SIGN for value in words.copy()}
    for a in sorted(words):
        for kind in ('negate', 'increment', 'decrement'):
            add(kind, a, 0, 'raw-word-all-bit-carry-borrow-boundaries')
        for b in (a, a^SIGN, (a+1)&((1<<64)-1), 0, SIGN):
            for kind in ('magnitude', 'equal'):
                add(kind, a, b, 'raw-magnitude-and-finite-numerical-equality')
    for e in range(1, 2047):
        add('power', e, 0, 'all-2046-normal-power-exponents')
    for e in (0, 2047, 2048, 0x7fffffff, 0x80000000, 0xffffffff):
        add('power', e, 0, 'reject-power-exponent-outside-stored-normal-range')
    for index, row in enumerate(rows): row['id'] = index
    validate_rows(rows)
    return rows


def validate_row(row):
    required = {'id', 'kind', *FIELDS}
    if type(row) is not dict or not required <= set(row) or set(row) - required - {'labels'}:
        raise ValueError('Malformed input record shape')
    word(row['id'], 32)
    if type(row['kind']) is not str or row['kind'] not in KINDS:
        raise ValueError('Unknown observation kind')
    inputs(row['kind'], *(row[field] for field in FIELDS))
    if 'labels' in row and (type(row['labels']) is not list or
            any(type(label) is not str or not label for label in row['labels']) or
            len(set(row['labels'])) != len(row['labels'])):
        raise ValueError('Malformed input labels')


def validate_rows(rows):
    if type(rows) is not list:
        raise ValueError('Expected input record list')
    ids = set()
    for row in rows:
        validate_row(row)
        if row['id'] in ids:
            raise ValueError('Duplicate input observation ID')
        ids.add(row['id'])


def expected_row(row):
    validate_row(row)
    result = checked(row['kind'], *(row[field] for field in FIELDS))
    prefix = [row['id'], KINDS[row['kind']]]
    return [*prefix, 0, 0, 0] if result is None else [*prefix, 1, *result]


def strict_json(text):
    if type(text) is not str:
        raise ValueError('Expected JSON text')
    def pairs(items):
        value = {}
        for key, item in items:
            if key in value:
                raise ValueError('Duplicate JSON key')
            value[key] = item
        return value
    def constant(value):
        raise ValueError('Nonfinite JSON constant')
    return json.loads(text, object_pairs_hook=pairs, parse_constant=constant)


def parse_output(text, selected):
    validate_rows(selected)
    if type(text) is not str:
        raise ValueError('Expected output text')
    lines = text.splitlines()
    groups = [selected[start:start+LINE] for start in range(0, len(selected), LINE)]
    if len(lines) != len(groups):
        raise ValueError('Wrong output line count/framing')
    actual = []
    for line, group in zip(lines, groups):
        values = strict_json(line)
        if type(values) is not list or len(values) != WIDTH * len(group):
            raise ValueError('Wrong output shape/count')
        for value in values:
            word(value, 32)
        for offset, row in enumerate(group):
            result = values[WIDTH*offset:WIDTH*(offset+1)]
            if result[0] != row['id'] or result[1] != KINDS[row['kind']] or result[2] not in (0, 1):
                raise ValueError('Wrong output ID, operation kind or tag')
            if result[2] == 0 and result[3:] != [0, 0]:
                raise ValueError('Noncanonical rejected payload')
            validate_observations([result])
            actual.append(result)
    return actual


def validate_observations(rows):
    if type(rows) is not list:
        raise ValueError('Expected observation list')
    ids = set()
    for row in rows:
        if type(row) is not list or len(row) != WIDTH:
            raise ValueError('Wrong observation shape')
        for value in row:
            word(value, 32)
        if row[0] in ids or row[1] not in KINDS.values() or row[2] not in (0, 1):
            raise ValueError('Wrong observation ID, operation kind or tag')
        if row[2] == 0 and row[3:] != [0, 0]:
            raise ValueError('Noncanonical rejected payload')
        if row[1] in {KINDS[k] for k in ('negate', 'magnitude', 'equal', 'increment', 'decrement')} and row[2] != 1:
            raise ValueError('Raw or Boolean operation cannot be rejected')
        if row[1] in (KINDS['magnitude'], KINDS['equal']) and (row[3] != 0 or row[4] > (2 if row[1] == KINDS['magnitude'] else 1)):
            raise ValueError('Noncanonical scalar output payload')
        ids.add(row[0])


def compare(expected, actual):
    validate_observations(expected)
    validate_observations(actual)
    if len(expected) != len(actual):
        raise ValueError('Incomplete comparison')
    differences = [dict(id=a[0], expected=a, actual=b) for a, b in zip(expected, actual) if a != b]
    if differences:
        raise ValueError(f'Exact mismatch: {differences[:8]} (total {len(differences)})')


def program(selected):
    validate_rows(selected)
    if not 1 <= len(selected) <= CHUNK:
        raise ValueError('Candidate program must contain 1..256 operations')
    expressions = {
        'mul': 'O.checked_multiply(ah, al, bh, bl)',
        'div': 'O.checked_divide(ah, al, bh, bl)',
        'identity': 'O.checked_identity(ah, al)',
        'promote': 'O.checked_promote(al)',
        'finite': 'O.checked_finite(ah, al)',
        'negate': 'Some{O.negate(ah, al)}',
        'magnitude': 'Some{F.Words{0, O.magnitude_order(ah, al, bh, bl)}}',
        'equal': 'Some{F.Words{0, Bool.to_u32(O.numerical_equal(ah, al, bh, bl))}}',
        'increment': 'Some{O.increment(ah, al)}',
        'decrement': 'Some{O.decrement(ah, al)}',
        'power': 'O.checked_power(al)',
    }
    source = '''import Base
import ../../src/binary64_fma.bend as F
import ../../src/binary64_ops.bend as O
type Task is Data:
'''
    for kind in KINDS:
        source += f'  {kind.title()}{{index: U32, ah: U32, al: U32, bh: U32, bl: U32}}\n'
    source += '''def observe(index: U32, kind: U32, value: Maybe<F.Words>, rest: List<U32>) -> List<U32>:
  match value:
    case None{}: Con{index, Con{kind, Con{0, Con{0, Con{0, rest}}}}}
    case Some{pair}:
      F.Words{high, low} = pair
      Con{index, Con{kind, Con{1, Con{high, Con{low, rest}}}}}
def one(task: Task, rest: List<U32>) -> List<U32>:
  match task:
'''
    for kind, number in KINDS.items():
        source += f'    case {kind.title()}{{index, ah, al, bh, bl}}: observe(index, {number}, {expressions[kind]}, rest)\n'
    source += '''def calculate(values: +List<Task>) -> List<U32>:
  match values:
    case Nil{}: Nil{}
    case Con{task, rest}: one(task, calculate(rest))
def main() -> IO(Unit):
  do IO<Unit>:
'''
    for start in range(0, len(selected), LINE):
        values = [row['kind'].title() + '{' + ','.join(str(value) for value in (row['id'], *(row[f] for f in FIELDS))) + '}'
                  for row in selected[start:start+LINE]]
        source += '    IO.print(List.show(~&1, ~U32, ~U32.show, calculate([' + ','.join(values) + '])))\n'
    return source


# Native controls intentionally exceed candidate arithmetic domains. The
# subnormal controls detect FTZ/DAZ at runtime rather than trusting compiler flags.
# kind 3 means a direct binary32-to-binary64 cast; its input is in the low word.
NATIVE_CONTROLS = (
    (0, 0x3ff0000000000001, 0x3ff8000000000000, 0x3ff8000000000002),
    (0, 0x3ff0000000000003, 0x3ff8000000000000, 0x3ff8000000000004),
    (0, 0x3ff0000000000001, 0x3ffffffffffffffe, 0x4000000000000000),
    (0, 0xbff0000000000001, 0x3ff8000000000000, 0xbff8000000000002),
    (1, 0x3ff0000000000000, 0x4008000000000000, 0x3fd5555555555555),
    (1, 0xbff0000000000000, 0x4008000000000000, 0xbfd5555555555555),
    (1, 0x3ff0000000000001, 0x3ff8000000000000, 0x3fe5555555555557),
    (1, 0x3ff0000000000000, 0x3ff0000000000001, 0x3feffffffffffffe),
    (0, 0x0000000000000000, 0x3ff0000000000000, 0x0000000000000000),
    (0, 0x0000000000000000, 0xbff0000000000000, 0x8000000000000000),
    (0, 0x8000000000000000, 0x3ff0000000000000, 0x8000000000000000),
    (0, 0x8000000000000000, 0xbff0000000000000, 0x0000000000000000),
    (1, 0x0000000000000000, 0x3ff0000000000000, 0x0000000000000000),
    (1, 0x0000000000000000, 0xbff0000000000000, 0x8000000000000000),
    (1, 0x8000000000000000, 0x3ff0000000000000, 0x8000000000000000),
    (1, 0x8000000000000000, 0xbff0000000000000, 0x0000000000000000),
    (0, 0x0000000000000001, 0x3ff0000000000000, 0x0000000000000001),
    (0, 0x8000000000000001, 0x3ff0000000000000, 0x8000000000000001),
    (0, 0x0010000000000000, 0x3fe0000000000000, 0x0008000000000000),
    (0, 0x000fffffffffffff, 0x4000000000000000, 0x001ffffffffffffe),
    (1, 0x0000000000000001, 0x3ff0000000000000, 0x0000000000000001),
    (1, 0x0010000000000000, 0x4000000000000000, 0x0008000000000000),
    (1, 0x8000000000000002, 0x4000000000000000, 0x8000000000000001),
    (1, 0x0010000000000000, 0x3ff0000000000001, 0x000fffffffffffff),
    (3, 0x00000000, 0, 0x0000000000000000),
    (3, 0x80000000, 0, 0x8000000000000000),
    (3, 0x00000001, 0, 0x36a0000000000000),
    (3, 0x80000001, 0, 0xb6a0000000000000),
    (3, 0x007fffff, 0, 0x380fffffc0000000),
    (3, 0x00800000, 0, 0x3810000000000000),
    (3, 0x3f800001, 0, 0x3ff0000020000000),
    (3, 0x7f7fffff, 0, 0x47efffffe0000000),
)
PREFLIGHT_COUNT = len(NATIVE_CONTROLS)
NATIVE = r'''#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <float.h>
#include <limits.h>
#include <fenv.h>
#include <inttypes.h>
#if defined(__x86_64__) || defined(__i386__)
#include <xmmintrin.h>
#elif !defined(__aarch64__)
#error Unsupported floating point control-register qualification
#endif
#ifdef __FAST_MATH__
#error Fast math invalidates this oracle
#endif
#pragma STDC FENV_ACCESS ON
#pragma STDC FP_CONTRACT OFF
_Static_assert(CHAR_BIT == 8 && sizeof(double) == 8 && sizeof(float) == 4, "word layout");
_Static_assert(FLT_RADIX == 2 && DBL_MANT_DIG == 53 && DBL_MIN_EXP == -1021 && DBL_MAX_EXP == 1024, "binary64");
_Static_assert(FLT_MANT_DIG == 24 && FLT_MIN_EXP == -125 && FLT_MAX_EXP == 128, "binary32");
_Static_assert(FLT_EVAL_METHOD == 0, "binary64 evaluation without excess precision");
static double mul_values(double a, double b) {
  volatile double va=a, vb=b; volatile double result=va*vb; return result;
}
static double div_values(double a, double b) {
  volatile double va=a, vb=b; volatile double result=va/vb; return result;
}
static double promote_value(float a) {
  volatile float va=a; volatile double result=(double)va; return result;
}
static double (* volatile runtime_mul)(double, double) = mul_values;
static double (* volatile runtime_div)(double, double) = div_values;
static double (* volatile runtime_promote)(float) = promote_value;
static uint64_t evaluate(unsigned kind, uint64_t a, uint64_t b) {
  double da,db,result; uint64_t bits;
  if (kind == 3) {
    uint32_t low=(uint32_t)a; float input; memcpy(&input,&low,4);
    volatile double computed=runtime_promote(input); result=computed;
  } else {
    memcpy(&da,&a,8); memcpy(&db,&b,8);
    volatile double computed=kind ? runtime_div(da,db) : runtime_mul(da,db); result=computed;
  }
  memcpy(&bits,&result,8); return bits;
}
static int expof(uint64_t a) { return (int)((a>>52)&2047)-1023; }
static uint64_t magnitude(uint64_t a) { return a & UINT64_C(0x7fffffffffffffff); }
static int finite_bits(uint64_t a) { return ((a>>52)&2047) != 2047; }
static int normal_or_zero(uint64_t a, int lo, int hi) {
  if (!magnitude(a)) return 1;
  unsigned e=(unsigned)((a>>52)&2047);
  return e && e != 2047 && expof(a) >= lo && expof(a) <= hi;
}
static int operation(unsigned kind, uint64_t a, uint64_t b, uint64_t *out) {
  switch (kind) {
  case 0:
    if (!normal_or_zero(a,-554,127) || !normal_or_zero(b,-554,127)) return 0;
    if (magnitude(a) && magnitude(b) && (expof(a)+expof(b)<-833 || expof(a)+expof(b)>127)) return 0;
    *out=evaluate(kind,a,b); return 1;
  case 1:
    if (!normal_or_zero(a,-225,127) || !normal_or_zero(b,-149,127) || !magnitude(b)) return 0;
    if (magnitude(a) && expof(a)>expof(b)) return 0;
    *out=evaluate(kind,a,b); return 1;
  case 2:
    if (!normal_or_zero(a,-1022,1023)) return 0;
    *out=a; return 1;
  case 3:
    if (((a>>23)&255) == 255) return 0;
    *out=evaluate(kind,a,b); return 1;
  case 4:
    if (!finite_bits(a)) return 0;
    *out=a; return 1;
  case 5: *out=a^UINT64_C(0x8000000000000000); return 1;
  case 6: *out=magnitude(a)==magnitude(b) ? 0 : magnitude(a)<magnitude(b) ? 1 : 2; return 1;
  case 7:
    if (!finite_bits(a) || !finite_bits(b)) { *out=0; return 1; }
    double da,db; memcpy(&da,&a,8); memcpy(&db,&b,8); *out=(da==db); return 1;
  case 8: *out=a+UINT64_C(1); return 1;
  case 9: *out=a-UINT64_C(1); return 1;
  case 10:
    if (a<1 || a>2046) return 0;
    *out=a<<52; return 1;
  }
  return -1;
}
int main(int argc, char **argv) {
  int initial=fegetround();
  if (argc != 2 || initial < 0 || fesetround(FE_TONEAREST) || fegetround() != FE_TONEAREST) return 2;
  uint64_t control; const char *control_name;
#if defined(__x86_64__) || defined(__i386__)
  control=_mm_getcsr(); control_name="mxcsr";
  if (control & ((1u<<15) | (1u<<6) | (3u<<13))) return 3;
#else
  __asm__ volatile("mrs %0, fpcr" : "=r"(control)); control_name="fpcr";
  if (control & ((1ull<<24) | (1ull<<19) | (3ull<<22) | 3ull)) return 3;
#endif
  double one=1.0; uint64_t one_bits; memcpy(&one_bits,&one,8);
  float fone=1.0f; uint32_t fone_bits; memcpy(&fone_bits,&fone,4);
  if (one_bits != UINT64_C(0x3ff0000000000000) || fone_bits != UINT32_C(0x3f800000)) return 4;
  static const uint64_t controls[][4] = {
@CONTROLS@
  };
  unsigned preflights=(unsigned)(sizeof controls/sizeof controls[0]);
  for (unsigned i=0;i<preflights;i++) {
    if (evaluate((unsigned)controls[i][0],controls[i][1],controls[i][2]) != controls[i][3]) {
      fprintf(stderr,"Runtime mul/div/promote preflight %u failed\n",i); return 7;
    }
  }
  printf("{\"rounding\":\"FE_TONEAREST\",\"initial_rounding\":%d,\"selected_rounding\":%d,\"control_name\":\"%s\",\"control\":%" PRIu64 ",\"ftz\":false,\"daz\":false,\"runtime_mul\":true,\"runtime_div\":true,\"runtime_promote\":true,\"binary64_evaluation\":true,\"preflight_count\":%u,\"char_bit\":%d,\"double_bytes\":%zu,\"float_bytes\":%zu,\"double_mantissa\":%d,\"float_mantissa\":%d,\"float_eval_method\":%d,\"one_bits\":\"%016" PRIx64 "\"}\n",initial,fegetround(),control_name,control,preflights,CHAR_BIT,sizeof(double),sizeof(float),DBL_MANT_DIG,FLT_MANT_DIG,FLT_EVAL_METHOD,one_bits);
  FILE *in=fopen(argv[1],"r"); if (!in) return 5;
  uint32_t index,kind,ah,al,bh,bl; int count;
  while ((count=fscanf(in,"%" SCNu32 " %" SCNu32 " %" SCNu32 " %" SCNu32 " %" SCNu32 " %" SCNu32,&index,&kind,&ah,&al,&bh,&bl)) == 6) {
    if (kind>10 || ((kind!=0 && kind!=1 && kind!=6 && kind!=7) && (bh || bl)) || ((kind==3 || kind==10) && ah)) { fclose(in); return 8; }
    uint64_t a=((uint64_t)ah<<32)|al,b=((uint64_t)bh<<32)|bl,bits=0;
    int accepted=operation(kind,a,b,&bits);
    if (accepted<0) { fclose(in); return 8; }
    printf("[%" PRIu32 ",%" PRIu32 ",%d,%" PRIu32 ",%" PRIu32 "]\n",index,kind,accepted,(uint32_t)(bits>>32),(uint32_t)bits);
  }
  if (count != EOF || ferror(in) || fclose(in)) return 6;
  return 0;
}
'''.replace('@CONTROLS@', ',\n'.join('    {' + ','.join(f'UINT64_C(0x{value:016x})' for value in row) + '}'
                                        for row in NATIVE_CONTROLS))



def parse_native(text, rows):
    validate_rows(rows)
    if type(text) is not str:
        raise ValueError('Expected native output text')
    lines = text.splitlines()
    if len(lines) != len(rows) + 1:
        raise ValueError('Wrong native line count')
    metadata = strict_json(lines[0])
    keys = {'rounding', 'initial_rounding', 'selected_rounding', 'control_name',
            'control', 'ftz', 'daz', 'runtime_mul', 'runtime_div', 'runtime_promote', 'binary64_evaluation', 'preflight_count',
            'char_bit', 'double_bytes', 'float_bytes', 'double_mantissa', 'float_mantissa', 'float_eval_method', 'one_bits'}
    if type(metadata) is not dict or set(metadata) != keys:
        raise ValueError('Malformed native environment metadata')
    if (metadata['rounding'] != 'FE_TONEAREST' or metadata['ftz'] is not False or
            metadata['daz'] is not False or metadata['runtime_mul'] is not True or
            metadata['runtime_div'] is not True or metadata['runtime_promote'] is not True or metadata['binary64_evaluation'] is not True or
            metadata['control_name'] not in ('mxcsr', 'fpcr')):
        raise ValueError('Unsupported native rounding/denormal/runtime environment')
    layout = {'char_bit':8, 'double_bytes':8, 'float_bytes':4, 'double_mantissa':53,
              'float_mantissa':24, 'float_eval_method':0, 'one_bits':'3ff0000000000000'}
    if any(type(metadata[key]) is not type(value) or metadata[key] != value for key, value in layout.items()):
        raise ValueError('Unqualified native binary32/binary64 layout')
    for key in ('initial_rounding', 'selected_rounding', 'control', 'preflight_count'):
        if type(metadata[key]) is not int or metadata[key] < 0:
            raise ValueError('Invalid native control metadata')
    word(metadata['control'], 32 if metadata['control_name'] == 'mxcsr' else 64)
    for key in ('initial_rounding', 'selected_rounding', 'preflight_count'):
        word(metadata[key], 32)
    if metadata['selected_rounding'] != 0 or metadata['preflight_count'] != PREFLIGHT_COUNT:
        raise ValueError('Unsupported native rounding or incomplete preflight')
    mask = ((1 << 15) | (1 << 6) | (3 << 13) if metadata['control_name'] == 'mxcsr'
            else (1 << 24) | (1 << 19) | (3 << 22) | 3)
    if metadata['control'] & mask:
        raise ValueError('Native rounding/denormal mode does not match metadata')
    groups = []
    for start in range(0, len(rows), LINE):
        combined = []
        for line in lines[1+start:1+min(start+LINE, len(rows))]:
            values = strict_json(line)
            if type(values) is not list or len(values) != WIDTH:
                raise ValueError('Malformed native record')
            combined.extend(values)
        groups.append(json.dumps(combined))
    return metadata, parse_output('\n'.join(groups), rows)


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write_json(path, value):
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + '\n')


def execute(command, work, name, timeout=600, env=None):
    command = [str(part) for part in command]
    for suffix in ('stdout', 'stderr'):
        (work/(name+'.'+suffix)).unlink(missing_ok=True)
    try:
        process = subprocess.run(command, cwd=ROOT, env=dict(os.environ, BEND_NO_TELEMETRY='1', **(env or {})),
                                 text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
    except subprocess.TimeoutExpired as error:
        for suffix, data in (('stdout', error.stdout), ('stderr', error.stderr)):
            (work/(name+'.'+suffix)).write_text(data.decode() if isinstance(data, bytes) else data or '')
        raise
    (work/(name+'.stdout')).write_text(process.stdout)
    (work/(name+'.stderr')).write_text(process.stderr)
    if process.returncode:
        raise ValueError(f'{name} exited {process.returncode}; retained stdout/stderr')
    return process.stdout


def compile_fresh(command, outputs, work, name, env=None):
    for path in outputs:
        path.unlink(missing_ok=True)
    execute(command, work, name, env=env)
    if any(not path.is_file() or path.stat().st_size == 0 for path in outputs):
        raise ValueError('Compiler succeeded without all fresh nonempty outputs')


def compiler_identity(command, work, name):
    resolved = shutil.which(str(command))
    if resolved is None:
        raise ValueError(f'Missing compiler/runtime: {command}')
    path = Path(resolved).resolve()
    return dict(path=str(path), sha256=digest(path), version=execute([command, '--version'], work, name).strip())


def candidate_environment(compiler):
    # Match the pinned Bend CLI's supported CPU compiler predicate.  An unsupported
    # CC would silently fall back to another clang, invalidating compiler evidence.
    match = re.search(r'^(Apple )?(?:\w+ )?clang version (\d+)', compiler['version'], re.M)
    if match is None or int(match[2]) < 14:
        raise ValueError('Recorded compiler is not a supported Bend CPU clang')
    return {'CC': compiler['path']}


def assert_unchanged(before):
    after = {path: digest(ROOT/path) for path in before}
    if after != before:
        raise ValueError('Source/harness/toolchain drift during probe')


def final_source_gate(hashes, bend_source, lock, compilers=None, work=None):
    assert_unchanged(hashes)
    checkout(bend_source, lock['bend']['revision'], lock['bend'].get('patch'))
    for name, (command, expected) in (compilers or {}).items():
        if compiler_identity(command, work, name+'-final-version') != expected:
            raise ValueError('Compiler/runtime executable drift during probe')


def retain_artifacts(report, work, names):
    """Pin evidence as it is consumed; do not bless later artifact changes."""
    retained = report.setdefault('artifacts', {})
    for name in names:
        current = digest(work/name)
        if name in retained and retained[name] != current:
            raise ValueError('Input/program/output artifact drift during probe: ' + name)
        retained[name] = current


def assert_artifacts_unchanged(report, work):
    for name, expected in report.get('artifacts', {}).items():
        if digest(work/name) != expected:
            raise ValueError('Input/program/output artifact drift during probe: ' + name)


def native_reference(rows, expected, work, clang):
    validate_rows(rows)
    source = work/'reference.c'; source.write_text(NATIVE)
    inputs = work/'native-input.txt'
    inputs.write_text(''.join(' '.join(str(v) for v in (r['id'], KINDS[r['kind']], *(r[f] for f in FIELDS)))+'\n' for r in rows))
    compiler = compiler_identity(clang, work, 'compiler-version')
    compile_fresh([clang, *FLAGS, source, '-lm', '-o', work/'reference'], [work/'reference'], work, 'native-compile')
    evidence = {'artifacts': {}}
    retain_artifacts(evidence, work, ['reference.c', 'reference', 'native-input.txt'])
    output = execute([work/'reference', inputs], work, 'native-run')
    environment, actual = parse_native(output, rows)
    compare(expected, actual)
    assert_artifacts_unchanged(evidence, work)
    retain_artifacts(evidence, work, ['native-run.stdout', 'native-run.stderr'])
    return dict(passed=True, observations=len(actual), compiler=compiler, flags=FLAGS, environment=environment,
                artifacts=evidence['artifacts'])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--bend-source', type=Path, required=True)
    parser.add_argument('--clang', default='clang')
    parser.add_argument('--native-only', action='store_true', help='qualify oracle/native only; never reports candidate pass')
    args = parser.parse_args()
    work = BUILD/'binary64-ops-probe'; work.mkdir(parents=True, exist_ok=True)
    report_path = work/'results.json'
    report = dict(schema=1, passed=False, lanes={}, phase='initializing')
    write_json(report_path, report)
    start = time.monotonic()
    try:
        lock = json.loads((ROOT/'toolchain.json').read_text())
        checkout(args.bend_source, lock['bend']['revision'], lock['bend'].get('patch'))
        hashes = source_gate()
        dependencies = (*DEPENDENCIES, lock['bend']['patch']['path']) if lock['bend'].get('patch') else DEPENDENCIES
        for path in dependencies:
            hashes[path] = digest(ROOT/path)
        bun = compiler_identity('bun', work, 'bun-version')
        if bun['version'] != lock['bun']['version']:
            raise ValueError('Bun version does not match pinned toolchain')
        rows = samples()
        expected = [expected_row(row) for row in rows]
        write_json(work/'inputs.json', rows)
        write_json(work/'expected.json', expected)
        report.update(phase='native-qualification', observations=len(rows),
                      accepted=sum(row[2] for row in expected), rejected=sum(row[2] == 0 for row in expected),
                      coverage=dict(Counter(label for row in rows for label in row['labels'])),
                      seed=SEED, bun=bun, chunk_limit=CHUNK, output_line_limit=LINE,
                      sources=hashes, inputs_sha256=digest(work/'inputs.json'), oracle_sha256=digest(work/'expected.json'),
                      scope='private checked multiply/divide, normal adapters, exact finite binary32 promotion, finite and raw-word helpers',
                      gpu='not run; no device claim', host=dict(platform=platform.platform(), machine=platform.machine(),
                      libc=platform.libc_ver(), python=platform.python_version()), chunks=[], artifacts={})
        retain_artifacts(report, work, ['inputs.json', 'expected.json'])
        write_json(report_path, report)
        report['native'] = native_reference(rows, expected, work, args.clang)
        for name, value in report['native']['artifacts'].items():
            report['artifacts'][name] = value
        assert_artifacts_unchanged(report, work)
        candidate_env = candidate_environment(report['native']['compiler'])
        report['candidate_compiler'] = dict(compiler=report['native']['compiler'], environment=candidate_env,
                                            flags_source='pinned bend2/main.ts cli_build CPU flags')
        write_json(work/'native-metadata.json', report['native'])
        report['native_metadata_sha256'] = digest(work/'native-metadata.json')
        compilers = {'compiler': (args.clang, report['native']['compiler']), 'bun': ('bun', bun)}
        names = ['inputs.json', 'expected.json', 'native-input.txt', 'reference.c', 'reference', 'native-metadata.json']
        names += [f'{prefix}.{suffix}' for prefix in ('compiler-version', 'bun-version', 'native-compile', 'native-run') for suffix in ('stdout', 'stderr')]
        retain_artifacts(report, work, names)
        print(f'Exact rational/volatile-runtime oracle agreement: {len(rows)} checked inputs', flush=True)
        if args.native_only:
            final_source_gate(hashes, args.bend_source, lock, compilers, work)
            names += [f'{prefix}-final-version.{suffix}' for prefix in ('compiler', 'bun') for suffix in ('stdout', 'stderr')]
            assert_artifacts_unchanged(report, work)
            retain_artifacts(report, work, names)
            report.update(phase='native-only-complete',
                          elapsed_seconds=round(time.monotonic()-start, 3))
            write_json(report_path, report)
            print('Native qualification complete; candidate lanes not run and overall passed remains false', flush=True)
            return
        report['phase'] = 'candidate'
        write_json(report_path, report)
        cli = ['bun', args.bend_source/'bend2/main.ts']
        proof = execute([*cli, ROOT/'PROOF.bend', '--check-only'], work, 'proof')
        if proof.strip() != 'All terms check.':
            raise ValueError('Incomplete proof verdict')
        report['proof'] = proof.strip()
        retain_artifacts(report, work, ['proof.stdout', 'proof.stderr'])
        totals = Counter()
        for batch, offset in enumerate(range(0, len(rows), CHUNK)):
            selected = rows[offset:offset+CHUNK]
            source = work/f'candidate-{batch:03}.bend'; source.write_text(program(selected))
            retain_artifacts(report, work, [source.name])
            binary, js = work/f'candidate-{batch:03}', work/f'candidate-{batch:03}.js'
            compile_fresh([*cli, source, '-o', binary, '-o', js], [binary, js], work, f'compile-{batch:03}', env=candidate_env)
            retain_artifacts(report, work, [binary.name, js.name, f'compile-{batch:03}.stdout', f'compile-{batch:03}.stderr'])
            for lane, command in (('cpu-1', [binary, '--gpu', 'off', '--threads', '1']),
                                  ('cpu-2', [binary, '--gpu', 'off', '--threads', '2']), ('javascript', ['bun', js])):
                actual = parse_output(execute(command, work, f'{lane}-{batch:03}'), selected)
                compare(expected[offset:offset+len(selected)], actual)
                retain_artifacts(report, work, [f'{lane}-{batch:03}.stdout', f'{lane}-{batch:03}.stderr'])
                totals[lane] += len(actual)
                report['lanes'][lane] = dict(passed=False, checked=totals[lane])
            report['chunks'].append(dict(index=batch, offset=offset, count=len(selected), passed=True))
            write_json(report_path, report)
            print(f'chunk {batch+1}: {len(selected)} observations match CPU-1/CPU-2/JS', flush=True)
        if set(totals) != {'cpu-1', 'cpu-2', 'javascript'} or any(value != len(rows) for value in totals.values()):
            raise ValueError('Incomplete lane coverage')
        final_source_gate(hashes, args.bend_source, lock, compilers, work)
        names += ['proof.stdout', 'proof.stderr']
        names += [f'{prefix}-final-version.{suffix}' for prefix in ('compiler', 'bun') for suffix in ('stdout', 'stderr')]
        for batch in range(len(report['chunks'])):
            names += [f'candidate-{batch:03}{suffix}' for suffix in ('.bend', '', '.js')]
            names += [f'{prefix}-{batch:03}.{suffix}' for prefix in ('compile', 'cpu-1', 'cpu-2', 'javascript') for suffix in ('stdout', 'stderr')]
        assert_artifacts_unchanged(report, work)
        retain_artifacts(report, work, names)
        report.update(passed=True, phase='complete',
                      elapsed_seconds=round(time.monotonic()-start, 3))
        for lane in report['lanes'].values():
            lane['passed'] = True
        write_json(report_path, report)
        print(f'PASS: {len(rows)} complete exact observations on each of three lanes', flush=True)
    except Exception as error:
        report.update(passed=False, error=str(error), elapsed_seconds=round(time.monotonic()-start, 3))
        write_json(report_path, report)
        raise


if __name__ == '__main__':
    main()
