#!/usr/bin/env python3
"""Check raylib.h's enumerations as Jonlib constants against compiled raylib.

Every raylib.h enumerator (except C's `bool`, which is Bend's Bool) is a
zero-argument U32 function `Enum.NAME()` in the generated last section of
jonlib.bend. The gate compiles each enumerator's value natively and compares
it with the Bend constant on CPU-1, CPU-2 and JavaScript; it also fails when
the catalog and the generated section disagree. `--write` regenerates the
section from api/reference.json and the native values.
"""
import json

import probekit
from probekit import ROOT, ProbeFailure

BEGIN = '# -----------------------------------------------------------------------------\n# raylib.h enumerations'
NOTE = '''# raylib.h enumerations (generated by tools/enums_probe.py --write)
#
# Each enumerator is a U32 constant named as in raylib.h under its enum's name,
# since raylib passes them as int and combines flags (ConfigFlags, Gesture).
'''


def enumerators():
    entries = json.loads((ROOT / 'api/reference.json').read_text())['entries']
    rows = entries if isinstance(entries, list) else list(entries.values())
    seen, result = set(), []
    for row in rows:
        if row['kind'] == 'enumerator' and row['header'] == 'raylib.h' and row['enum'] != 'bool' and row['name'] not in seen:
            seen.add(row['name'])
            result.append((row['enum'], row['name']))
    return result


def native_values(probe, names):
    lines = ['#include "raylib.h"', '#include <stdio.h>', 'int main(void){']
    lines += [f'printf("%lld\\n",(long long){name});' for _, name in names]
    values = [int(v) for v in probe.native('\n'.join(lines + ['return 0;}']) + '\n').split()]
    if len(values) != len(names) or any(v < 0 or v > 0xFFFFFFFF for v in values):
        raise ProbeFailure('enums: native values missing or outside U32')
    return values


def section(names, values):
    text, current = '\n' + BEGIN.split('\n')[0] + '\n' + NOTE, None
    for (enum, name), value in zip(names, values):
        if enum != current:
            text += f'\n# {enum}\n'
            current = enum
        text += f'def {enum}.{name}() -> U32:\n  {value}\n'
    return text


def write(names, values):
    path = ROOT / 'jonlib.bend'
    source = path.read_text()
    marker = '\n' + BEGIN.split('\n')[0] + '\n# raylib.h enumerations'
    if marker in source:
        source = source[:source.index(marker)]
    path.write_text(source.rstrip('\n') + '\n' + section(names, values))


def generated(names):
    source = (ROOT / 'jonlib.bend').read_text()
    found = [line[4:line.index('(')] for line in source.split('# raylib.h enumerations (generated', 1)[-1].splitlines()
             if line.startswith('def ')]
    if found != [f'{enum}.{name}' for enum, name in names]:
        raise ProbeFailure('enums: the generated jonlib.bend section is stale; rerun tools/enums_probe.py --write')


def render(selected, gpu):
    body = 'import Base\nimport ../../jonlib.bend as J\ndef main() -> IO(Unit):\n  do IO<Unit>:\n'
    for enum, name in selected:
        body += f'    IO.print(U32.show(J.{enum}.{name}()))\n'
    return body


def main():
    def configure(parser):
        parser.add_argument('--write', action='store_true', help='Regenerate the jonlib.bend enumeration section')
    args = probekit.arguments(__doc__, configure)
    probe = probekit.Probe('enums', args)
    names = enumerators()
    values = native_values(probe, names)
    if args.write:
        write(names, values)
    generated(names)
    lanes = probe.candidates(render, names, batch=len(names), parse=lambda text, selected: [int(v) for v in text.split()])
    lanes = {lane: rows for lane, rows in lanes.items() if lane != 'gpu'}
    probe.compare(values, lanes, describe=lambda i: '.'.join(names[i]))
    probe.finish(enumerators=len(names), enums=len({enum for enum, _ in names}))


if __name__ == '__main__':
    main()
