#!/usr/bin/env python3
"""Check the raylib, rlgl, rgestures and rcamera enumerations as Jonlib constants.

Every enumerator (except C's `bool`, which is Bend's Bool) is a zero-argument
U32 function `Enum.NAME()` in the generated last section of jonlib.bend. Each
header compiles standalone (rgestures.h and rcamera.h with their *_STANDALONE
switch, which is when they declare their own enums) and prints its values.
An enumerator another header already declares under the same enum name is
not generated again: its value must equal the first declaration's. The gate
compares every generated constant with the native value on CPU-1, CPU-2 and
JavaScript, and fails when the catalog and the generated section disagree.
`--write` regenerates the section from api/reference.json and the native values.
"""
import json

import probekit
from probekit import ROOT, ProbeFailure

RULE = '# -----------------------------------------------------------------------------'
TITLE = '# Header enumerations (generated by tools/enums_probe.py --write)'
OLD_TITLES = ('# raylib.h enumerations (generated', TITLE[:-1])
NOTE = '''#
# Each enumerator is a U32 constant named as in its header under its enum's
# name, since raylib passes them as int and combines flags (ConfigFlags,
# Gesture). raylib.h comes first; rlgl.h, rgestures.h and rcamera.h add the
# enums raylib.h lacks (their duplicates of raylib.h share its constants).
'''
# header: (prefix lines of its standalone program, linked against raylib)
HEADERS = {
    'raylib.h': (['#include "raylib.h"'], True),
    'rlgl.h': (['#include "rlgl.h"'], False),
    'rgestures.h': (['#define RGESTURES_STANDALONE', '#include "rgestures.h"'], False),
    'rcamera.h': (['#include <stdbool.h>', '#define RCAMERA_STANDALONE', '#include "rcamera.h"'], False),
}


def enumerators():
    """[(header, enum, name)] in catalog order, without C's bool."""
    entries = json.loads((ROOT / 'api/reference.json').read_text())['entries']
    rows = entries if isinstance(entries, list) else list(entries.values())
    seen, result = set(), []
    for row in rows:
        key = (row['header'], row.get('enum'), row['name'])
        if row['kind'] == 'enumerator' and row['header'] in HEADERS and row['enum'] != 'bool' and key not in seen:
            seen.add(key)
            result.append(key)
    return sorted(result, key=lambda key: list(HEADERS).index(key[0]))


def native_values(probe, names):
    """{(header, enum, name): value} from one standalone program per header."""
    values = {}
    for header, (prefix, linked) in HEADERS.items():
        selected = [key for key in names if key[0] == header]
        lines = prefix + ['#include <stdio.h>', 'int main(void){']
        lines += [f'printf("%lld\\n",(long long){name});' for _, _, name in selected]
        text = probe.native('\n'.join(lines + ['return 0;}']) + '\n', 'reference-' + header.split('.')[0], link_raylib=linked)
        found = [int(v) for v in text.split()]
        if len(found) != len(selected) or any(v < 0 or v > 0xFFFFFFFF for v in found):
            raise ProbeFailure(f'enums: {header} native values missing or outside U32')
        values.update(zip(selected, found))
    return values


def constants(names, values):
    """Generated (enum, name, value) in order; duplicates must agree with the first."""
    first, result = {}, []
    for key in names:
        _, enum, name = key
        if (enum, name) in first:
            if first[(enum, name)] != values[key]:
                raise ProbeFailure(f'enums: {key[0]} {enum}.{name} = {values[key]} differs from {first[(enum, name)]}')
            continue
        first[(enum, name)] = values[key]
        result.append((enum, name, values[key]))
    return result


def section(generated):
    text, current = '\n' + RULE + '\n' + TITLE + '\n' + NOTE, None
    for enum, name, value in generated:
        if enum != current:
            text += f'\n# {enum}\n'
            current = enum
        text += f'def {enum}.{name}() -> U32:\n  {value}\n'
    return text


def write(generated):
    path = ROOT / 'jonlib.bend'
    source = path.read_text()
    for title in OLD_TITLES:
        marker = '\n' + RULE + '\n' + title
        if marker in source:
            source = source[:source.index(marker)]
    path.write_text(source.rstrip('\n') + '\n' + section(generated))


def check_generated(generated):
    source = (ROOT / 'jonlib.bend').read_text()
    if TITLE not in source:
        raise ProbeFailure('enums: the jonlib.bend section is missing; rerun tools/enums_probe.py --write')
    found = [line[4:line.index('(')] for line in source.split(TITLE, 1)[1].splitlines() if line.startswith('def ')]
    if found != [f'{enum}.{name}' for enum, name, _ in generated]:
        raise ProbeFailure('enums: the generated jonlib.bend section is stale; rerun tools/enums_probe.py --write')


def render(selected, gpu):
    body = 'import Base\nimport ../../jonlib.bend as J\ndef main() -> IO(Unit):\n  do IO<Unit>:\n'
    for enum, name, _ in selected:
        body += f'    IO.print(U32.show(J.{enum}.{name}()))\n'
    return body


def main():
    def configure(parser):
        parser.add_argument('--write', action='store_true', help='Regenerate the jonlib.bend enumeration section')
    args = probekit.arguments(__doc__, configure)
    probe = probekit.Probe('enums', args)
    names = enumerators()
    generated = constants(names, native_values(probe, names))
    if args.write:
        write(generated)
    check_generated(generated)
    lanes = probe.candidates(render, generated, batch=160, parse=lambda text, selected: [int(v) for v in text.split()])
    lanes = {lane: rows for lane, rows in lanes.items() if lane != 'gpu'}
    probe.compare([value for _, _, value in generated], lanes, describe=lambda i: '.'.join(generated[i][:2]))
    probe.finish(enumerators=len(names), constants=len(generated), enums=len({enum for enum, _, _ in generated}),
                 headers={header: sum(key[0] == header for key in names) for header in HEADERS})


if __name__ == '__main__':
    main()
