#!/usr/bin/env python3
"""Track the pinned raylib examples as Bend ports, like the API ledger tracks APIs.

Every example in raylib's examples/examples_list.txt gets one row in
api/examples.json: the raylib API functions its .c source calls (matched
against the ledger's function names for raylib.h, raymath.h, rlgl.h,
rcamera.h and rgestures.h), and a status:

- ported: examples/<name>.bend exists and tools/examples_probe.py replays it
  against the native example (the `examples` gate);
- ready: every API the example calls is at least partial in the ledger, so it
  can be ported now;
- waiting: some API it calls is not-started or blocked (listed in `missing`).

`build --raylib-source <pinned raylib>` re-reads the example sources;
`refresh` recomputes the statuses from the stored API lists and the current
ledger (run it after `tools/api_plan.py build`); `check` (used by
tools/check_project.py, no raylib checkout needed) fails when either output is
stale.
"""
import argparse
import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / 'api/examples.json'
OUT_DOC = ROOT / 'docs/EXAMPLES.md'
HEADERS = ('raylib.h', 'raymath.h', 'rlgl.h', 'rcamera.h', 'rgestures.h')


def examples_list(raylib):
    rows = []
    for line in (raylib / 'examples/examples_list.txt').read_text().splitlines():
        if not line.strip() or line.startswith('#'):
            continue
        category, name = line.split(';')[:2]
        rows.append((category, name))
    return rows


def ledger_functions():
    entries = json.loads((ROOT / 'api/ledger.json').read_text())['entries']
    functions = {}
    for row in entries:
        if row.get('kind') == 'function' and row.get('header') in HEADERS:
            functions.setdefault(row['name'], row['status'])
    return functions


def ported_examples():
    """Names in tools/examples_probe.py's EXAMPLES table whose Bend port exists."""
    source = (ROOT / 'tools/examples_probe.py').read_text()
    tree = ast.parse(source)
    names = set()
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, 'id', None) == 'EXAMPLES' for t in node.targets):
            names = {k.value for k in node.value.keys}
    return {n for n in names if (ROOT / f'examples/{n}.bend').is_file()}


def calls(source, functions):
    source = re.sub(r'/\*.*?\*/', '', source, flags=re.S)
    source = re.sub(r'//[^\n]*', '', source)
    used = set(re.findall(r'\b([A-Za-z_][A-Za-z0-9_]*)\s*\(', source))
    return sorted(used & set(functions))


def status_rows(rows):
    """Statuses from each row's API list, the current ledger and the ported examples."""
    functions = ledger_functions()
    ported = ported_examples()
    out = []
    for r in rows:
        if r['status'] == 'missing-source':
            out.append(r)
            continue
        missing = [a for a in r['apis'] if functions.get(a) not in ('partial', 'complete')]
        status = 'ported' if r['name'] in ported else ('ready' if not missing else 'waiting')
        out.append(dict(r, status=status, missing=missing))
    return out


def plan(raylib):
    functions = ledger_functions()
    rows = []
    for category, name in examples_list(raylib):
        path = raylib / 'examples' / category / f'{name}.c'
        if not path.is_file():
            rows.append(dict(name=name, category=category, status='missing-source', apis=[], missing=[]))
            continue
        rows.append(dict(name=name, category=category, status='', apis=calls(path.read_text(errors='replace'), functions), missing=[]))
    return status_rows(rows)


def document(rows):
    counts = {s: sum(r['status'] == s for r in rows) for s in ('ported', 'ready', 'waiting', 'missing-source')}
    blockers = {}
    for r in rows:
        for a in r['missing']:
            blockers[a] = blockers.get(a, 0) + 1
    lines = ['# raylib examples as Bend ports', '',
             'Generated by `tools/examples_plan.py build` from the pinned',
             '`examples/examples_list.txt`; do not edit by hand. An example is **ported**',
             'when `examples/<name>.bend` exists and the `examples` gate replays it against',
             'the native example ([DRIVER.md](DRIVER.md)); **ready** when every raylib API it',
             'calls is at least partial in the ledger; **waiting** otherwise.', '',
             f'Totals: {len(rows)} examples; {counts["ported"]} ported, {counts["ready"]} ready, '
             f'{counts["waiting"]} waiting' + (f', {counts["missing-source"]} without source' if counts['missing-source'] else '') + '.', '',
             '## APIs that unblock the most examples', '', '| API | Examples waiting on it |', '|---|---|']
    for api, n in sorted(blockers.items(), key=lambda kv: (-kv[1], kv[0]))[:40]:
        lines.append(f'| `{api}` | {n} |')
    lines += ['', '## Examples', '', '| Example | Category | Status | Missing APIs |', '|---|---|---|---|']
    for r in rows:
        lines.append(f'| `{r["name"]}` | {r["category"]} | {r["status"]} | {", ".join(f"`{m}`" for m in r["missing"])} |')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=('build', 'refresh', 'check'))
    parser.add_argument('--raylib-source', type=Path)
    args = parser.parse_args()
    if args.command == 'build':
        if args.raylib_source is None:
            parser.error('build needs --raylib-source (the pinned raylib checkout)')
        rows = plan(args.raylib_source)
    else:
        rows = status_rows(json.loads(OUT_JSON.read_text())['examples'])
    text = json.dumps(dict(schema=1, examples=rows), indent=1, ensure_ascii=False) + '\n'
    doc = document(rows)
    if args.command in ('build', 'refresh'):
        OUT_JSON.write_text(text)
        OUT_DOC.write_text(doc)
    elif OUT_JSON.read_text() != text or OUT_DOC.read_text() != doc:
        sys.exit('examples plan is stale: run python3 tools/examples_plan.py refresh')
    counts = {s: sum(r['status'] == s for r in rows) for s in ('ported', 'ready', 'waiting')}
    print(f'Examples plan {args.command}: {len(rows)} examples; ' + ', '.join(f'{v} {k}' for k, v in counts.items()))


if __name__ == '__main__':
    main()
