"""Minimal TrueType fonts generated for tools/ttf_probe.py.

Every font here is built from code (no third-party font data): an sfnt with
head, hhea, maxp, hmtx, cmap, loca and glyf tables whose outlines are seeded
pseudo-random contours (on- and off-curve points, repeated and short-vector
flags, contours starting off the curve, single-point contours), composite
glyphs (byte and short offsets, scale, x/y scale and 2x2 transforms, nested
components, the unsupported point-matching form) and cmap subtables in
formats 0, 4, 6, 12 and 13. Provenance: generated by this file, public to the
repository under its license; no glyph shapes are copied from any font.
"""
import random
import struct


def _pad4(data):
    return data + b'\0' * (-len(data) % 4)


def sfnt(tables, version=0x00010000):
    """Assemble tables {tag: bytes} into an sfnt file (tags in given order)."""
    tags = list(tables)
    n = len(tags)
    head = struct.pack('>IHHHH', version, n, 16, 0, 0)
    offset = 12 + 16 * n
    records, body = b'', b''
    for tag in tags:
        data = tables[tag]
        records += struct.pack('>4sIII', tag.encode('latin-1'), 0, offset + len(body), len(data))
        body += _pad4(data)
    return head + records + body


def head_table(units_per_em=1000, loc_format=0, bbox=(0, 0, 0, 0)):
    return struct.pack('>IIIIHHQQhhhhHHhhh', 0x00010000, 0x00010000, 0, 0x5F0F3CF5, 0, units_per_em, 0, 0,
                       *bbox, 0, 8, 2, loc_format, 0)


def hhea_table(ascent, descent, line_gap, long_metrics):
    return struct.pack('>IhhhHhhhhhhhhhhhH', 0x00010000, ascent, descent, line_gap, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
                       long_metrics)


def maxp_table(num_glyphs):
    return struct.pack('>IH', 0x00005000, num_glyphs)


def hmtx_table(advances, lsbs, long_metrics):
    out = b''
    for i, (a, l) in enumerate(zip(advances, lsbs)):
        out += struct.pack('>Hh', a & 0xFFFF, l) if i < long_metrics else struct.pack('>h', l)
    return out


# -----------------------------------------------------------------------------
# cmap subtables

def cmap_format0(mapping):
    ids = bytes(mapping.get(c, 0) & 0xFF for c in range(256))
    return struct.pack('>HHH', 0, 6 + 256, 0) + ids


def cmap_format6(mapping, first, count):
    ids = b''.join(struct.pack('>H', mapping.get(c, 0)) for c in range(first, first + count))
    return struct.pack('>HHHHH', 6, 10 + 2 * count, 0, first, count) + ids


def cmap_format4(mapping, use_delta=True):
    """Segments of consecutive codepoints; glyph ids via idDelta or idRangeOffset."""
    cps = sorted(c for c in mapping if c <= 0xFFFF)
    segs = []
    for c in cps:
        if segs and c == segs[-1][1] + 1:
            segs[-1][1] = c
        else:
            segs.append([c, c])
    segs.append([0xFFFF, 0xFFFF])
    n = len(segs)
    search = 2 * (1 << (n.bit_length() - 1))
    selector = n.bit_length() - 1
    shift = 2 * n - search
    ends = b''.join(struct.pack('>H', e) for _, e in segs)
    starts = b''.join(struct.pack('>H', s) for s, _ in segs)
    deltas, offsets, glyph_ids = b'', [], []
    for i, (s, e) in enumerate(segs):
        if s == 0xFFFF:
            deltas += struct.pack('>h', 1)
            offsets.append(None)
            continue
        ids = [mapping[c] for c in range(s, e + 1)]
        if use_delta and all(ids[k] - ids[0] == k for k in range(len(ids))):
            d = (ids[0] - s) & 0xFFFF
            deltas += struct.pack('>H', d)
            offsets.append(None)
        else:
            deltas += struct.pack('>h', 0)
            offsets.append(len(glyph_ids))
            glyph_ids += ids
    range_offsets = b''
    for i, o in enumerate(offsets):
        if o is None:
            range_offsets += struct.pack('>H', 0)
        else:
            range_offsets += struct.pack('>H', 2 * (n - i) + 2 * o)
    body = ends + b'\0\0' + starts + deltas + range_offsets + b''.join(struct.pack('>H', g) for g in glyph_ids)
    return struct.pack('>HHHHHHH', 4, 14 + len(body), 0, 2 * n, search, selector, shift) + body


def cmap_format12(mapping, fmt=12):
    cps = sorted(mapping)
    groups = []
    for c in cps:
        g = mapping[c]
        if groups and c == groups[-1][1] + 1 and (fmt == 13 and g == groups[-1][2] or fmt == 12 and g == groups[-1][2] + c - groups[-1][0]):
            groups[-1][1] = c
        else:
            groups.append([c, c, g])
    body = b''.join(struct.pack('>III', *g) for g in groups)
    return struct.pack('>HHIII', fmt, 0, 16 + len(body), 0, len(groups)) + body


def cmap_table(subtables):
    """subtables: [(platform, encoding, bytes)]"""
    out = struct.pack('>HH', 0, len(subtables))
    offset = 4 + 8 * len(subtables)
    body = b''
    for p, e, data in subtables:
        out += struct.pack('>HHI', p, e, offset + len(body))
        body += data
    return out + body


# -----------------------------------------------------------------------------
# glyf

def simple_glyph(contours, bbox=None, instructions=b'', compress=True):
    """contours: [[(x, y, on), ...], ...]"""
    pts = [p for c in contours for p in c]
    if not pts:
        return b''
    ends, k = [], -1
    for c in contours:
        k += len(c)
        ends.append(k)
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    if bbox is None:
        bbox = (min(xs), min(ys), max(xs), max(ys))
    flags, xdata, ydata = [], b'', b''
    px = py = 0
    for x, y, on in pts:
        f = 1 if on else 0
        dx, dy = x - px, y - py
        if compress and dx == 0:
            f |= 16
        elif compress and -255 <= dx <= 255:
            f |= 2 | (16 if dx > 0 else 0)
            xdata += bytes([abs(dx)])
        else:
            xdata += struct.pack('>h', dx)
        if compress and dy == 0:
            f |= 32
        elif compress and -255 <= dy <= 255:
            f |= 4 | (32 if dy > 0 else 0)
            ydata += bytes([abs(dy)])
        else:
            ydata += struct.pack('>h', dy)
        flags.append(f)
        px, py = x, y
    fdata, i = b'', 0
    while i < len(flags):
        run = 1
        while compress and i + run < len(flags) and flags[i + run] == flags[i] and run < 256:
            run += 1
        if run > 1:
            fdata += bytes([flags[i] | 8, run - 1])
        else:
            fdata += bytes([flags[i]])
        i += run
    out = struct.pack('>hhhhh', len(contours), *bbox)
    out += b''.join(struct.pack('>H', e) for e in ends)
    out += struct.pack('>H', len(instructions)) + instructions
    return out + fdata + xdata + ydata


def composite_glyph(components, bbox=(0, 0, 100, 100)):
    """components: dicts with gidx, dx, dy and optional words (bool), scale
    (one value), xy (two), two (four) as F2DOT14 ints, point (matching-point form)."""
    out = struct.pack('>hhhhh', -1, *bbox)
    for i, c in enumerate(components):
        flags = 0
        more = i + 1 < len(components)
        args = b''
        if c.get('point'):
            flags |= 0
            args = struct.pack('>BB', c['dx'] & 0xFF, c['dy'] & 0xFF)
        else:
            flags |= 2
            if c.get('words') or not (-128 <= c['dx'] <= 127 and -128 <= c['dy'] <= 127):
                flags |= 1
                args = struct.pack('>hh', c['dx'], c['dy'])
            else:
                args = struct.pack('>bb', c['dx'], c['dy'])
        tail = b''
        if 'scale' in c:
            flags |= 8
            tail = struct.pack('>h', c['scale'])
        elif 'xy' in c:
            flags |= 64
            tail = struct.pack('>hh', *c['xy'])
        elif 'two' in c:
            flags |= 128
            tail = struct.pack('>hhhh', *c['two'])
        if more:
            flags |= 32
        out += struct.pack('>HH', flags, c['gidx']) + args + tail
    return out


def glyf_loca(glyphs, loc_format):
    glyf, offsets = b'', []
    for g in glyphs:
        offsets.append(len(glyf))
        glyf += g + b'\0' * (len(g) % 2 if loc_format == 0 else -len(g) % 4)
    offsets.append(len(glyf))
    if loc_format == 0:
        loca = b''.join(struct.pack('>H', o // 2) for o in offsets)
    else:
        loca = b''.join(struct.pack('>I', o) for o in offsets)
    return glyf, loca


# -----------------------------------------------------------------------------
# Outlines

def random_contours(rng, em, kind):
    """Seeded contours in [0, em) squares: kind 'curves', 'lines' or 'mixed'."""
    contours = []
    for _ in range(rng.randint(1, 3)):
        cx, cy = rng.randint(em // 8, em * 5 // 8), rng.randint(-em // 8, em * 5 // 8)
        r = rng.randint(em // 12, em // 3)
        n = rng.randint(3, 9)
        pts = []
        for k in range(n):
            import math
            a = 2 * math.pi * k / n + rng.uniform(-0.3, 0.3)
            rr = r * rng.uniform(0.4, 1.1)
            on = True if kind == 'lines' else (rng.random() < (0.5 if kind == 'mixed' else 0.35))
            pts.append((int(cx + rr * math.cos(a)), int(cy + rr * math.sin(a)), on))
        if rng.random() < 0.5:
            pts.reverse()
        contours.append(pts)
    if kind != 'lines' and rng.random() < 0.3:
        # a single-point contour; off the curve it reads the next contour's
        # first point, so it never comes last (stb would read past the points)
        contours.insert(rng.randrange(len(contours)), [(rng.randint(0, em // 2), rng.randint(0, em // 2), rng.random() < 0.5)])
    return contours


def box_contours(rng, em):
    """Pixel-font style rectangles (lines only, axis-aligned edges)."""
    cell = em // 8
    out = []
    for _ in range(rng.randint(1, 4)):
        x, y = rng.randint(0, 5) * cell, rng.randint(-1, 5) * cell
        w, h = rng.randint(1, 3) * cell, rng.randint(1, 3) * cell
        out.append([(x, y, True), (x, y + h, True), (x + w, y + h, True), (x + w, y, True)])
    return out


def build_font(seed, *, em=1000, codepoints=range(32, 127), cmap='4', loc_format=0, kind='mixed',
               ascent=None, descent=None, line_gap=0, long_metrics=None, extra_glyphs=(), composites=True,
               bad_bbox=0.0, empty=(32,), compress=True, extra_tables=None):
    """A complete TrueType font; returns (bytes, {codepoint: glyph index})."""
    rng = random.Random(seed)
    glyphs = [simple_glyph([[(0, 0, True), (em // 2, 0, True), (em // 2, em // 2, True), (0, em // 2, True)]])]  # .notdef
    advances, lsbs = [em // 2], [0]
    mapping = {}
    for cp in codepoints:
        if cp in empty:
            data = b''
        elif kind == 'boxes':
            data = simple_glyph(box_contours(rng, em), compress=compress)
        else:
            contours = random_contours(rng, em, kind)
            bbox = None
            if rng.random() < bad_bbox:
                xs = [p[0] for c in contours for p in c]
                ys = [p[1] for c in contours for p in c]
                shrink = rng.randint(em // 20, em // 6)
                bbox = (min(xs) + shrink, min(ys) + shrink // 2, max(xs) - shrink, max(ys) - shrink // 3)
            data = simple_glyph(contours, bbox=bbox, compress=compress)
        mapping[cp] = len(glyphs)
        glyphs.append(data)
        advances.append(rng.randint(em // 4, em) if cp not in empty or rng.random() < 0.8 else 0)
        lsbs.append(rng.randint(-20, 40))
    if composites:
        simple = [mapping[c] for c in codepoints if c not in empty]
        comps = [
            [dict(gidx=simple[0], dx=10, dy=-5)],
            [dict(gidx=simple[1], dx=200, dy=-300, words=True), dict(gidx=simple[2], dx=-40, dy=60)],
            [dict(gidx=simple[3], dx=0, dy=0, scale=8192)],
            [dict(gidx=simple[4], dx=30, dy=20, xy=(20000, 12000))],
            [dict(gidx=simple[5], dx=-10, dy=100, two=(14000, 3000, -4000, 15000))],
            [dict(gidx=simple[6], dx=5, dy=5), dict(gidx=simple[7], dx=300, dy=0, scale=-16384)],
        ]
        for spec in comps:
            mapping[0x100 + len(glyphs)] = len(glyphs)
            glyphs.append(composite_glyph(spec))
        nested = len(glyphs)
        mapping[0x100 + nested] = nested
        glyphs.append(composite_glyph([dict(gidx=nested - 1, dx=50, dy=50), dict(gidx=simple[8], dx=-20, dy=-20, scale=12000)]))
        mapping[0x100 + len(glyphs)] = len(glyphs)
        glyphs.append(composite_glyph([dict(gidx=simple[9], dx=3, dy=4, point=True), dict(gidx=simple[10], dx=100, dy=0)]))
    for cp, data in extra_glyphs:
        mapping[cp] = len(glyphs)
        glyphs.append(data)
        advances.append(rng.randint(em // 4, em))
        lsbs.append(0)
    while len(advances) < len(glyphs):
        advances.append(rng.randint(em // 4, em))
        lsbs.append(rng.randint(-20, 40))
    n = len(glyphs)
    long_metrics = n if long_metrics is None else long_metrics
    glyf, loca = glyf_loca(glyphs, loc_format)
    ascent = em * 4 // 5 if ascent is None else ascent
    descent = -em // 5 if descent is None else descent
    if cmap == '4':
        sub = [(3, 1, cmap_format4({c: g for c, g in mapping.items() if c <= 0xFFFF}))]
    elif cmap == '4r':
        sub = [(0, 3, cmap_format4({c: g for c, g in mapping.items() if c <= 0xFFFF}, use_delta=False))]
    elif cmap == '0':
        sub = [(0, 0, cmap_format0({c: g for c, g in mapping.items() if c < 256}))]
    elif cmap == '6':
        first = min(mapping)
        count = min(max(c for c in mapping if c < 0x10000) - first + 1, 400)
        sub = [(3, 1, cmap_format6(mapping, first, count))]
    elif cmap in ('12', '13'):
        sub = [(1, 0, cmap_format0({})), (3, 10, cmap_format12(mapping, int(cmap)))]
    elif cmap == '2':
        sub = [(3, 1, struct.pack('>HHH', 2, 6, 0))]
    else:
        raise ValueError(cmap)
    tables = {'head': head_table(em, loc_format), 'hhea': hhea_table(ascent, descent, line_gap, long_metrics),
              'maxp': maxp_table(n), 'hmtx': hmtx_table(advances, lsbs, long_metrics), 'cmap': cmap_table(sub),
              'loca': loca, 'glyf': glyf}
    if extra_tables:
        tables.update(extra_tables)
    return sfnt(tables), mapping
