#!/usr/bin/env python3
"""Compare Jonlib's TrueType/BDF font loading with raylib 6.0's rtext.c and
its stb_truetype.h / stb_rect_pack.h.

Same reference as tools/font_probe.py: pinned raylib on PLATFORM=Memory
(rlsw) built with CMAKE_C_FLAGS=-ffp-contract=off and checked free of fused
multiply-adds; release build, so STBTT_assert is a no-op. Each scene runs
InitWindow, a list of operations and prints one row: a log of every logging
operation followed by the framebuffer (rlCopyFramebuffer, RGBA).

Fonts: TrueType files generated by tools/ttf_fonts.py (cmap formats 0, 4
(delta and range offsets), 6, 12, 13 and an unsupported 2; short and long
loca; quadratic contours with on/off-curve points, repeated and short flags,
contours starting off the curve, single-point contours; composites with
byte/short offsets, scale, x/y scale, 2x2 and point-matching forms, nested;
glyph boxes smaller than the outline, which drive the rasterizer's clipping
path; pixel-style line fonts for SDF; a space with an outline; negative
advances) plus two OFL fonts read from the pinned raylib checkout
(examples/text/resources/anonymous_pro_bold.ttf and DotGothic16-Regular.ttf,
SIL Open Font License; read in place, not redistributed). BDF files and an
XNA-style PNG are generated here.

Logged: LoadFontData glyphs (value, offsets, advance, image size and every
byte) for FONT_DEFAULT, FONT_BITMAP and FONT_SDF at several sizes and
codepoint lists; GenImageFontAtlas images (every byte) and rectangles (bits)
for both packing methods over loaded and synthetic glyph sets (ties in the
rectangle sort, the qsort depth limit, atlas growth, clipped and unpacked
glyphs); fonts from LoadFontFromMemory, LoadFontEx and LoadFont (fields,
whole glyph table with every glyph image, GetGlyphInfo), MeasureTextEx,
ImageTextEx, ExportFontAsCode's file bytes and DrawTextEx frames.

Contracts: operations marked 'R' are not run natively; Jonlib must refuse
them (undefined C behavior: reads past the font data, the BDF reader's NULL
pointer write; or outside Jonlib's profile: CFF outlines, SDF glyphs needing
the cubic solver). CPU-1, CPU-2 and JavaScript lanes.
"""
import hashlib
import json
import random
import shutil
import struct
import zlib

from conformance import gradient_reference
import font_probe as fpb
import frame_probe as fp
import probekit
import ttf_fonts as T
from probekit import ROOT, ProbeFailure

C = fp.C
f32 = fp.f32
cf = fp.cf
bf = fp.bf
WHITE, BLACK, RED, BLUE = C(255, 255, 255), C(0, 0, 0), C(230, 41, 55), C(0, 121, 241)
RESOURCES = 'examples/text/resources'

def T8(text):
    return list(text.encode('utf-8')) if isinstance(text, str) else list(text)

# -----------------------------------------------------------------------------
# Generated files

def bdf_text(lines):
    return ('\n'.join(lines) + '\n').encode('latin-1')

def png(width, height, pixels, gray=False):
    """A minimal 8-bit PNG: RGBA of canonical 0xRRGGBBAA words, or gray bytes."""
    if gray:
        raw = b''.join(b'\0' + bytes(pixels[y * width:(y + 1) * width]) for y in range(height))
    else:
        raw = b''.join(b'\0' + b''.join(struct.pack('>I', pixels[y * width + x]) for x in range(width)) for y in range(height))

    def chunk(tag, data):
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xFFFFFFFF)
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 0 if gray else 6, 0, 0, 0)) +
            chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def fnt(page, chars, line_height=18, scale_h=32, pages=1, count=None, header=None, extra=()):
    """An AngelCode BMFont text file; chars are (id, x, y, w, h, xoff, yoff, xadv)."""
    lines = ['info face="Generated" size=16 bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=1,1',
             header or f'common lineHeight={line_height} base=14 scaleW=64 scaleH={scale_h} pages={pages} packed=0',
             f'page id=0 file="{page}"', f'chars count={len(chars) if count is None else count}']
    lines += [f'char id={c[0]}   x={c[1]}     y={c[2]}     width={c[3]}     height={c[4]}     xoffset={c[5]}     yoffset={c[6]}    xadvance={c[7]}    page=0  chnl=15'
              for c in chars]
    return ('\n'.join(lines + list(extra)) + '\n').encode('latin-1')

def font_files(work, raylib_source):
    """Write the generated fonts; return {name: absolute path}."""
    d = work / 'fonts'
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True)
    paths = {}

    def put(name, data):
        (d / name).write_bytes(data)
        paths[name] = str(d / name)

    specs = {
        'f4.ttf': dict(seed=1, cmap='4', kind='mixed', bad_bbox=0.2),
        'f4r.ttf': dict(seed=2, cmap='4r', loc_format=1, kind='curves'),
        'f0.ttf': dict(seed=3, cmap='0', kind='lines'),
        'f6.ttf': dict(seed=4, cmap='6', kind='mixed', long_metrics=40),
        'f12.ttf': dict(seed=5, cmap='12', loc_format=1, kind='curves', codepoints=list(range(32, 127)) + [0xE9, 0x3000, 0x1F600], empty=(32, 0x3000)),
        'f13.ttf': dict(seed=6, cmap='13', kind='mixed'),
        'boxes.ttf': dict(seed=7, cmap='4', kind='boxes', composites=False, em=2048, ascent=1700, descent=-400),
        'big.ttf': dict(seed=8, cmap='4', kind='curves', em=2048, ascent=1900, descent=-500, line_gap=90, bad_bbox=0.3),
        'f2.ttf': dict(seed=9, cmap='2', kind='mixed'),
        'outline_space.ttf': dict(seed=10, cmap='4', kind='lines', empty=()),
        'raw.ttf': dict(seed=11, cmap='4', kind='mixed', compress=False),
    }
    for name, spec in specs.items():
        put(name, T.build_font(**spec)[0])
    data, _ = T.build_font(seed=12, cmap='4', kind='mixed')
    put('upper.TTF', data)
    put('truncated.ttf', data[:len(data) * 2 // 3])
    # A space whose advance is negative (hmtx is read as signed).
    neg, mapping = T.build_font(seed=13, cmap='4', kind='lines')
    tables = {}
    count = struct.unpack('>H', neg[4:6])[0]
    for i in range(count):
        tag, _, off, length = struct.unpack('>4sIII', neg[12 + 16 * i:28 + 16 * i])
        tables[tag.decode()] = (off, length)
    off = tables['hmtx'][0] + 4 * mapping[32]
    put('negative_space.ttf', neg[:off] + struct.pack('>H', 0xFFF0) + neg[off + 2:])
    # No cmap (stbtt_InitFont fails) and an OpenType CFF font (no glyf).
    put('nocmap.ttf', T.sfnt({'head': T.head_table(), 'hhea': T.hhea_table(800, -200, 0, 1), 'hmtx': b'\0\0\0\0', 'maxp': T.maxp_table(1)}))
    put('cff.otf', T.sfnt({'CFF ': b'\x01\x00\x04\x01' + b'\0' * 32, 'cmap': T.cmap_table([(3, 1, T.cmap_format4({65: 1}))]),
                           'head': T.head_table(), 'hhea': T.hhea_table(800, -200, 0, 2), 'hmtx': b'\0' * 8, 'maxp': T.maxp_table(2)},
                          version=0x4F54544F))
    put('empty.ttf', b'')
    # BDF: without characters (the zeroed glyph array), with a space only (NULL:
    # the default font), with a requested character (raylib writes through
    # NULL), and without ENDFONT (GetLine reads past the data).
    put('plain.bdf', bdf_text(['STARTFONT 2.1', 'COMMENT a SIZE comment', 'FONT -gen-plain', 'SIZE 13 75 75', 'PIXEL_SIZE 99',
                               'FONTBOUNDINGBOX 8 13 0 -2', 'FONT_ASCENT 11', 'ENDFONT', 'trailing']))
    put('hex.bdf', bdf_text(['STARTFONT 2.1', 'SIZE 0x10', 'SIZE   012', 'ENDFONT']))
    put('space.bdf', bdf_text(['STARTFONT 2.1', 'SIZE 9', 'STARTCHAR space', 'ENCODING 32', 'BBX 4 9 0 -2', 'BITMAP', '00', 'ENDCHAR',
                               'STARTCHAR x', 'ENCODING 1000', 'BITMAP', 'ff', 'ENDCHAR', 'ENDFONT']))
    put('crash.bdf', bdf_text(['STARTFONT 2.1', 'SIZE 9', 'STARTCHAR A', 'ENCODING 65', 'BITMAP', 'ff', 'ENDCHAR', 'ENDFONT']))
    put('open.bdf', bdf_text(['STARTFONT 2.1', 'SIZE 9']))
    # An XNA-style image font for LoadFont (MAGENTA key, first char 32).
    spec = fpb.font_image(40, 16, 0xFF00FFFF, 1, 1, 6, [[2, 3, 1, 4, 2], [3, 3, 2]], seed=5)
    put('image_font.png', png(spec['width'], spec['height'], fpb.font_pixels(spec)))
    # BMFont: a 64x32 page (RGBA and GRAYSCALE), glyph rectangles inside it.
    page = [((x * 37 + y * 101) & 0xFF) << 24 | ((x * 13) & 0xFF) << 16 | ((y * 29) & 0xFF) << 8 | (0 if (x + y) % 5 == 0 else 128 + (x * y) % 128)
            for y in range(32) for x in range(64)]
    put('bm_page.png', png(64, 32, page))
    put('bm_gray.png', png(64, 32, [(x * 7 + y * 19) & 0xFF for y in range(32) for x in range(64)], gray=True))
    chars = [(32, 0, 0, 0, 0, 0, 14, 4), (65, 1, 1, 7, 9, 0, 3, 8), (66, 9, 1, 6, 9, 1, 3, 7), (103, 16, 2, 5, 11, 0, 5, 6), (0x263A, 22, 0, 12, 12, -1, 2, 11),
             (63, 40, 20, 8, 10, 0, 4, 9), (33, 63, 31, 1, 1, 2, 2, 3)]
    put('gen.fnt', fnt('bm_page.png', chars))
    put('gray.fnt', fnt('bm_gray.png', chars[:4], line_height=12))
    put('header.fnt', fnt('bm_page.png', chars, header='common lineHeight=18 base=14'))
    put('nopage.fnt', fnt('missing_page.png', [(32, 0, 0, 0, 0, 0, 0, 4), (65, 5, 5, 0, 7, 0, 0, 4)]))
    put('nopage_pixels.fnt', fnt('missing_page.png', chars))
    put('badline.fnt', fnt('bm_page.png', chars[:3] + [(70, 1, 1, 1, 1, 0, 0, 1)], extra=(), count=5))
    put('two_pages.fnt', fnt('bm_page.png', chars, pages=2))
    put('outside.fnt', fnt('bm_page.png', chars + [(90, 60, 30, 8, 8, 0, 0, 9)]))
    for name in ('anonymous_pro_bold.ttf', 'DotGothic16-Regular.ttf'):
        paths[name] = str(raylib_source / RESOURCES / name)
    paths['missing.ttf'] = str(d / 'missing.ttf')
    paths['missing.png'] = str(d / 'missing.png')
    return paths

# -----------------------------------------------------------------------------
# Scenes

ASCII = list(range(32, 127))

def synth(rng, n, sizes):
    """Synthetic GRAYSCALE glyph images: (w, h, seed) triples."""
    return [(rng.choice(sizes)[0], rng.choice(sizes)[1], rng.randrange(1000)) for _ in range(n)]

def scenes(paths, libm):
    out = []
    rng = random.Random(0x77F1)

    def add(name, width, height, ops):
        out.append(dict(id=name, width=width, height=height, ops=ops))

    P = paths
    composites = list(range(0x160, 0x16A))
    # LoadFontData: glyphs and images.
    for name in ('f4.ttf', 'f4r.ttf', 'f0.ttf', 'f6.ttf', 'f12.ttf', 'f13.ttf', 'raw.ttf'):
        add(f'data-{name}', 4, 4, [('data', P[name], 20, [], 0, 0), ('data', P[name], 13, ASCII[:40] + composites, len(ASCII[:40]) + 10, 1)])
    add('data-sizes', 4, 4, [('data', P['f4.ttf'], s, [32, 65, 66, 87, 103, 0x161, 0x165], 7, 0) for s in (1, 6, 9, 24, 33, 48, 77, 0)])
    add('data-big', 4, 4, [('data', P['big.ttf'], 64, [33, 64, 77, 87, 103, 0x162], 6, 0), ('data', P['big.ttf'], 120, [65, 0x163], 2, 0)])
    add('data-real', 4, 4, [('data', P['anonymous_pro_bold.ttf'], 32, [], 0, 0), ('data', P['anonymous_pro_bold.ttf'], 11, [65, 103, 0xE9, 0x20AC, 32], 5, 1)])
    add('data-counts', 4, 4, [('data', P['f12.ttf'], 18, [], 120, 0), ('data', P['f12.ttf'], 18, [0x3000, 0xE9, 0x1F600, 5, 0xFFFFFFFF, 0x80000000, 300], 7, 0),
                              ('data', P['f12.ttf'], 18, [65, 66, 67, 68], 2, 0), ('data', P['f4.ttf'], 15, [], -3 & 0xFFFFFFFF, 1)])
    add('data-sdf', 4, 4, [('data', P['boxes.ttf'], 24, ASCII[:30], 30, 2), ('data', P['f0.ttf'], 16, [], 0, 2),
                           ('data', P['DotGothic16-Regular.ttf'], 20, [32, 65, 103, 0x3042, 0x3000], 5, 2)])
    add('data-odd', 4, 4, [('data', P['f2.ttf'], 20, [], 0, 0), ('data', P['nocmap.ttf'], 20, [], 0, 0), ('data', P['outline_space.ttf'], 20, [32, 33], 2, 0), ('data', P['outline_space.ttf'], 20, [32, 33], 2, 1, 'R'),
                           ('data', P['negative_space.ttf'], 20, [32, 65], 2, 0)])
    add('data-refused', 4, 4, [('data', P['truncated.ttf'], 20, [], 0, 0, 'R'), ('data', P['cff.otf'], 20, [], 0, 0, 'R'),
                               ('data', P['f4.ttf'], 20, [65, 66], 2, 2, 'R'), ('data', P['f4.ttf'], 20, [65, 66, 67], 5, 0, 'R')])
    # GenImageFontAtlas over loaded glyphs.
    for k, (name, size, pad, method, count) in enumerate((('f4.ttf', 20, 4, 0, 0), ('f4.ttf', 20, 4, 1, 0), ('f12.ttf', 13, 0, 0, 0), ('f12.ttf', 13, 0, 1, 0),
                                                         ('f13.ttf', 31, 2, 1, 0), ('anonymous_pro_bold.ttf', 18, 1, 1, 0), ('anonymous_pro_bold.ttf', 18, 4, 0, 40),
                                                         ('boxes.ttf', 24, 3, 1, 30))):
        add(f'atlas-{k}', 4, 4, [('atlas_data', P[name], size, [], 0, 0, count, size, pad, method)])
    # Synthetic glyph sets: ties, the depth limit, growth, clipping, unpacked.
    for k in range(10):
        n = rng.randrange(8, 120)
        sizes = [(rng.randrange(0, 9), rng.randrange(0, 12)) for _ in range(rng.randrange(1, 5))]
        add(f'synth-{k}', 4, 4, [('atlas_synth', synth(rng, n, sizes), n, rng.randrange(4, 20), rng.randrange(0, 5), m) for m in (0, 1)])
    add('synth-grow', 4, 4, [('atlas_synth', [(3, 30, i) for i in range(40)], 40, 8, 1, 0), ('atlas_synth', [(5, 7, i) for i in range(9)] + [(70, 9, 1)], 10, 8, 2, 0),
                             ('atlas_synth', [(9, 9, i) for i in range(30)] + [(40, 40, 3)], 31, 6, 0, 1)])
    # Heights built against FreeBSD's quicksort (McIlroy's adversary) exhaust
    # Apple's introsort depth limit: the heapsort fallback sorts part of them.
    killer30 = [100, 84, 98, 71, 96, 73, 94, 72, 92, 74, 90, 75, 88, 76, 86, 99, 97, 95, 93, 91, 89, 87, 85, 78, 79, 80, 81, 82, 83, 77]
    killer40 = [100, 61, 98, 63, 96, 62, 94, 64, 92, 65, 90, 66, 88, 67, 86, 68, 84, 69, 82, 80, 99, 97, 95, 93, 91, 89, 87, 85, 83, 81,
                71, 72, 73, 74, 75, 76, 77, 78, 79, 70]
    add('synth-depth', 4, 4, [('atlas_synth', [(3, h, i) for i, h in enumerate(killer30)], 30, 100, 0, 1),
                              ('atlas_synth', [(2 + i % 2, h, i) for i, h in enumerate(killer40)], 40, 100, 0, 1),
                              ('atlas_synth', [(5, 6, 1)], 1, 8, 1, 1), ('atlas_synth', [(4, 4, 1), (4, 4, 2)], 0, 8, 1, 1, 'R')])
    # LoadFontFromMemory / LoadFontEx / LoadFont, then the font in use.
    hello = T8('Hello, TrueType!\nfox jumps 0123')
    for k, (name, ext, size) in enumerate((('f4.ttf', '.ttf', 20), ('f12.ttf', '.TTF', 16), ('anonymous_pro_bold.ttf', '.otf', 22), ('f0.ttf', '.ttf', 9))):
        add(f'mem-{k}', 96, 48, [('begin',), ('clear', C(250, 250, 240)), ('mem', 0, P[name], ext, size, [], 0), ('info', 0), ('table', 0),
                                 ('glyph', 0, 32), ('glyph', 0, 65), ('glyph', 0, 0x2603), ('measure', 0, hello, float(size), 1.0),
                                 ('text_ex', 0, hello, 2.0, 3.0, float(size), 1.0, BLACK), ('text_ex', 0, T8('Wq'), 40.5, 30.25, size * 1.5, -1.0, C(200, 30, 60, 180)),
                                 ('image_text_ex', 0, T8('Ab'), float(size), 2.0, BLUE), ('code', 0, f'gen_font-{k}.h'), ('unload', 0), ('end',)])
    add('mem-codepoints', 64, 32, [('begin',), ('clear', WHITE), ('mem', 0, P['f12.ttf'], '.ttf', 24, [65, 0x3000, 66, 0xE9, 32, 0x1F600], 6), ('info', 0), ('table', 0),
                                   ('text_ex', 0, T8('A\u3000B\u00e9 \U0001F600'), 1.0, 1.0, 24.0, 0.0, RED), ('end',)])
    add('mem-other', 16, 16, [('mem', 0, P['f4.ttf'], '.png', 20, [], 0), ('info', 0), ('mem', 1, P['nocmap.ttf'], '.ttf', 20, [], 0), ('info', 1),
                              ('mem', 0, P['plain.bdf'], '.bdf', 20, [], 0), ('info', 0), ('table', 0), ('code', 0, 'plain_bdf.h'),
                              ('mem', 1, P['hex.bdf'], '.BDF', 20, [], 40), ('info', 1), ('mem', 1, P['space.bdf'], '.bdf', 20, [], 0), ('info', 1)])
    add('mem-refused', 16, 16, [('mem', 0, P['f2.ttf'], '.ttf', 20, [], 0, 'R'), ('mem', 0, P['negative_space.ttf'], '.ttf', 20, [], 0, 'R'),
                                ('mem', 0, P['crash.bdf'], '.bdf', 20, [], 0, 'R'), ('mem', 0, P['open.bdf'], '.bdf', 20, [], 0, 'R'),
                                ('mem', 0, P['cff.otf'], '.otf', 20, [], 0, 'R')])
    add('ex-load', 64, 40, [('begin',), ('clear', WHITE), ('ex', 0, P['big.ttf'], 30, [72, 105, 33], 3), ('info', 0), ('table', 0),
                            ('text_ex', 0, T8('Hi!'), 2.0, 2.0, 30.0, 2.0, BLACK), ('ex', 1, P['missing.ttf'], 20, [], 0), ('info', 1),
                            ('ex', 1, P['empty.ttf'], 20, [], 0), ('info', 1), ('end',)])
    add('load', 48, 24, [('begin',), ('clear', WHITE), ('load', 0, P['f6.ttf']), ('info', 0), ('measure', 0, T8('load'), 32.0, 0.0),
                         ('load', 1, P['upper.TTF']), ('info', 1), ('text_ex', 1, T8('ok'), 1.0, 1.0, 20.0, 1.0, BLACK), ('unload', 1),
                         ('load', 1, P['plain.bdf']), ('info', 1), ('unload', 1), ('load', 1, P['image_font.png']), ('info', 1), ('table', 1),
                         ('code', 1, 'image_font.h'), ('unload', 1), ('load', 1, P['missing.png']), ('info', 1), ('code', 1, 'default.h'), ('end',)])
    add('bmfont', 64, 32, [('begin',), ('clear', C(20, 30, 40)), ('load', 0, P['gen.fnt']), ('info', 0), ('table', 0), ('glyph', 0, 32), ('glyph', 0, 0x263A),
                           ('measure', 0, T8('AB g\u263a?'), 18.0, 1.0), ('text_ex', 0, T8('AB g\u263a?!'), 1.0, 2.0, 18.0, 1.0, WHITE),
                           ('text_ex', 0, T8('BgA'), 10.5, 15.0, 27.0, -2.0, C(255, 200, 100, 200)), ('code', 0, 'gen_bm.h'),
                           ('load', 1, P['gray.fnt']), ('info', 1), ('table', 1), ('text_ex', 1, T8('gAB'), 30.0, 20.0, 12.0, 0.0, WHITE), ('unload', 1),
                           ('load', 1, P['header.fnt']), ('info', 1), ('load', 1, P['nopage.fnt']), ('info', 1), ('end',)])
    add('bmfont-refused', 8, 8, [('load', 0, P['nopage_pixels.fnt'], 'R'), ('load', 0, P['badline.fnt'], 'R'), ('load', 0, P['two_pages.fnt'], 'R'),
                                 ('load', 0, P['outside.fnt'], 'R')])
    return out

def declared(op):
    return op[-1] == 'R'

def strip(op):
    return op[:-1] if declared(op) else op

# -----------------------------------------------------------------------------
# Native reference

C_PREFIX = r'''#include "raylib.h"
#include "rlgl.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned fb(float f) { unsigned u; memcpy(&u, &f, 4); return u; }
static float bf(unsigned u) { float f; memcpy(&f, &u, 4); return f; }
static void hexbytes(const unsigned char *p, int n) { for (int i = 0; i < n; i++) printf("%02x", p[i]); }
static void dump(int w, int h)
{
    unsigned char *p = malloc(w*h*4);
    rlCopyFramebuffer(0, 0, w, h, PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, p);
    for (int i = 0; i < w*h; i++) { unsigned char t = p[4*i]; p[4*i] = p[4*i + 2]; p[4*i + 2] = t; }
    printf(" F ");
    hexbytes(p, w*h*4);
    printf("\n");
    free(p);
}
static void image_out(Image im)
{
    if ((im.data == NULL) || (im.width <= 0) || (im.height <= 0)) { printf(" i-"); return; }
    printf(" i%d,%d,%d,", im.width, im.height, im.format);
    hexbytes(im.data, GetPixelDataSize(im.width, im.height, im.format));
}
static void font_info(Font f) { printf(" f%d,%d,%d,%u,%d", f.baseSize, f.glyphCount, f.glyphPadding, f.texture.id, (int)IsFontValid(f)); }
static void glyph_row(GlyphInfo g, Rectangle r)
{
    printf(",%d,%d,%d,%d,%u,%u,%u,%u", g.value, g.offsetX, g.offsetY, g.advanceX, fb(r.x), fb(r.y), fb(r.width), fb(r.height));
    image_out(g.image);
}
static void table(Font f)
{
    printf(" T");
    for (int i = 0; i < f.glyphCount; i++) { printf(" "); glyph_row(f.glyphs[i], f.recs[i]); }
}
static void glyph(Font f, int cp)
{
    printf(" g%d", GetGlyphIndex(f, cp));
    GlyphInfo g = GetGlyphInfo(f, cp);
    glyph_row(g, GetGlyphAtlasRec(f, cp));
    printf(",%d,%d", g.image.width, g.image.height);
}
static void glyph_data(GlyphInfo *g, int n)
{
    if (g == NULL) { printf(" D-"); return; }
    printf(" D%d", n);
    for (int i = 0; i < n; i++)
    {
        printf(" %d,%d,%d,%d,%d,%d,", g[i].value, g[i].offsetX, g[i].offsetY, g[i].advanceX, g[i].image.width, g[i].image.height);
        if ((g[i].image.data != NULL) && (g[i].image.width > 0) && (g[i].image.height > 0)) hexbytes(g[i].image.data, g[i].image.width*g[i].image.height);
        else printf("-");
    }
}
static void atlas_out(Image atlas, Rectangle *recs, int n)
{
    image_out(atlas);
    printf(" r");
    for (int i = 0; i < n; i++) printf("%u,%u,%u,%u;", fb(recs[i].x), fb(recs[i].y), fb(recs[i].width), fb(recs[i].height));
}
static void data_op(const char *path, int size, int *cps, int count, int type)
{
    int n = 0, size_data = 0;
    unsigned char *bytes = LoadFileData(path, &size_data);
    GlyphInfo *g = LoadFontData(bytes, size_data, size, cps, count, type, &n);
    glyph_data(g, n);
    UnloadFontData(g, n);
    UnloadFileData(bytes);
}
static void atlas_data(const char *path, int size, int *cps, int count, int type, int acount, int asize, int pad, int method)
{
    int n = 0, size_data = 0;
    unsigned char *bytes = LoadFileData(path, &size_data);
    GlyphInfo *g = LoadFontData(bytes, size_data, size, cps, count, type, &n);
    Rectangle *recs = NULL;
    Image atlas = GenImageFontAtlas(g, &recs, acount, asize, pad, method);
    atlas_out(atlas, recs, (acount > 0)? acount : 95);
    UnloadImage(atlas); RL_FREE(recs);
    UnloadFontData(g, n);
    UnloadFileData(bytes);
}
static void atlas_synth(const int *specs, int n, int acount, int asize, int pad, int method)
{
    GlyphInfo *g = RL_CALLOC(n, sizeof(GlyphInfo));
    for (int i = 0; i < n; i++)
    {
        int w = specs[3*i], h = specs[3*i + 1], seed = specs[3*i + 2];
        g[i].value = 32 + i;
        g[i].image.width = w; g[i].image.height = h; g[i].image.mipmaps = 1; g[i].image.format = PIXELFORMAT_UNCOMPRESSED_GRAYSCALE;
        if (w*h > 0)
        {
            unsigned char *p = RL_MALLOC(w*h);
            for (int k = 0; k < w*h; k++) p[k] = (unsigned char)(((unsigned)k*2654435761u + (unsigned)seed*40503u) >> 13);
            g[i].image.data = p;
        }
    }
    Rectangle *recs = NULL;
    Image atlas = GenImageFontAtlas(g, &recs, acount, asize, pad, method);
    atlas_out(atlas, recs, (acount > 0)? acount : 95);
    UnloadImage(atlas); RL_FREE(recs);
    UnloadFontData(g, n);
}
static void code_op(Font f, const char *dir, const char *name)
{
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", dir, name);
    bool ok = ExportFontAsCode(f, path);
    int n = 0;
    unsigned char *d = ok ? LoadFileData(path, &n) : NULL;
    printf(" X");
    if (d != NULL) { hexbytes(d, n); UnloadFileData(d); } else printf("-");
}
'''

def ctext(data):
    return '"' + ''.join(f'\\{c:03o}' for c in data) + '"'

def cint(v):
    return str(v - (1 << 32) if v >= 1 << 31 else v)

def cints(values):
    return '(int[]){ ' + ''.join(f'{cint(v)}, ' for v in values) + '0 }' if values else 'NULL'

def cstr(text):
    return json.dumps(text)

def c_op(op, codes):
    name, a = op[0], op[1:]
    if declared(op):
        return '    printf(" R");'
    calls = {
        'begin': lambda: 'BeginDrawing();', 'end': lambda: 'EndDrawing();', 'clear': lambda: f'ClearBackground({fp.cc(a[0])});',
        'data': lambda: f'data_op({cstr(a[0])}, {cint(a[1])}, {cints(a[2])}, {cint(a[3])}, {a[4]});',
        'atlas_data': lambda: f'atlas_data({cstr(a[0])}, {cint(a[1])}, {cints(a[2])}, {cint(a[3])}, {a[4]}, {cint(a[5])}, {cint(a[6])}, {cint(a[7])}, {a[8]});',
        'atlas_synth': lambda: (f'atlas_synth((const int[]){{ {", ".join(str(v) for s in a[0] for v in s)} }}, {len(a[0])}, {cint(a[1])}, {cint(a[2])}, '
                                f'{cint(a[3])}, {a[4]});'),
        'mem': lambda: (f'{{ int n = 0; unsigned char *d = LoadFileData({cstr(a[1])}, &n); f[{a[0]}] = LoadFontFromMemory({cstr(a[2])}, d, n, {cint(a[3])}, '
                        f'{cints(a[4])}, {cint(a[5])}); UnloadFileData(d); printf(" L"); }}'),
        'ex': lambda: f'f[{a[0]}] = LoadFontEx({cstr(a[1])}, {cint(a[2])}, {cints(a[3])}, {cint(a[4])}); printf(" L");',
        'load': lambda: f'f[{a[0]}] = LoadFont({cstr(a[1])}); printf(" L");',
        'unload': lambda: f'UnloadFont(f[{a[0]}]); f[{a[0]}] = (Font){{ 0 }};',
        'info': lambda: f'font_info(f[{a[0]}]);', 'table': lambda: f'table(f[{a[0]}]);', 'glyph': lambda: f'glyph(f[{a[0]}], {cint(a[1])});',
        'measure': lambda: f'{{ Vector2 v = MeasureTextEx(f[{a[0]}], {ctext(a[1])}, {cf(a[2])}, {cf(a[3])}); printf(" v%u,%u", fb(v.x), fb(v.y)); }}',
        'text_ex': lambda: f'DrawTextEx(f[{a[0]}], {ctext(a[1])}, {fp.cv(a[2], a[3])}, {cf(a[4])}, {cf(a[5])}, {fp.cc(a[6])});',
        'image_text_ex': lambda: f'{{ Image im = ImageTextEx(f[{a[0]}], {ctext(a[1])}, {cf(a[2])}, {cf(a[3])}, {fp.cc(a[4])}); image_out(im); UnloadImage(im); }}',
        'code': lambda: f'code_op(f[{a[0]}], {cstr(codes)}, {cstr(a[1])});',
    }
    return '    ' + calls[name]()

def c_scene(scene, codes):
    lines = [f'    {{ Font f[2] = {{ 0 }}; (void)f;', f'    InitWindow({scene["width"]}, {scene["height"]}, "");', '    printf("S");']
    lines += [c_op(op, codes) for op in scene['ops']]
    lines += [f'    dump({scene["width"]}, {scene["height"]});', '    CloseWindow(); }']
    return '\n'.join(lines)

def native_rows(probe, items, codes):
    source = C_PREFIX + '\nint main(void)\n{\n    SetTraceLogLevel(LOG_NONE);\n' + '\n'.join(c_scene(s, codes) for s in items) + '\n    return 0;\n}\n'
    lines = [line for line in probe.native(source, 'reference', extra_flags=('-ffp-contract=off',)).splitlines() if line.startswith('S')]
    if len(lines) != len(items):
        raise ProbeFailure(f'ttf: reference printed {len(lines)} rows for {len(items)} scenes')
    return lines

def logf_control(probe):
    """GenImageFontAtlas's (int)powf(2, ceilf(logf(x)/logf(2))) at the powers of
    two must be the power itself (Jonlib's atlas size assumes it)."""
    source = ('#include <math.h>\n#include <stdio.h>\nint main(void)\n{\n    volatile float two = 2.0f;\n'
              '    for (int k = 0; k <= 15; k++) { volatile float x = ldexpf(1.0f, k); printf("%d ", (int)powf(two, ceilf(logf(x)/logf(two)))); }\n'
              '    printf("\\n");\n    return 0;\n}\n')
    got = probe.native(source, 'logf', extra_flags=('-ffp-contract=off', '-fno-builtin'), link_raylib=False).split()
    if got != [str(1 << k) for k in range(16)]:
        raise ProbeFailure(f'ttf: the host logf gives atlas sizes {got} at powers of two')

# -----------------------------------------------------------------------------
# Bend candidate

PROGRAM = fp.PROGRAM.replace('import ../../src/trig.bend as Trig\n', 'import ../../src/trig.bend as Trig\nimport ../../src/text.bend as TC\n'
                             'import ../../src/fonts.bend as FontCore\n') + '''
def hex.byte(+b: U32, rest: String) -> String:
  SCon{hex.digit(((b >> 4n) .&. 15 : U32)), SCon{hex.digit((b .&. 15 : U32)), rest}}

def hex.bytes.go(reversed: List<U32>, acc: String) -> String:
  match reversed:
    case Nil{}: acc
    case Con{+b, rest}: hex.bytes.go(rest, hex.byte(b, acc))

def hex.bytes(bytes: List<U32>) -> String:
  hex.bytes.go(List.reverse(&1, U32, bytes), "")

def hex.text.go(s: String, acc: List<U32>) -> List<U32>:
  match s:
    case SNil{}: acc
    case SCon{Chr{c}, rest}: hex.text.go(rest, Con{c, acc})

def hex.text(s: String) -> String:
  hex.bytes(List.reverse(&1, U32, hex.text.go(s, Nil{})))

def sint(+v: U32) -> String:
  Bool.pick(String, (v >= 2147483648 : U32), "-" ++ U32.show((0 - v : U32)), U32.show(v))

def fbits(+x: F32) -> String:
  U32.show(F32.bits(x))

def image.out(s: J.Surface) -> String:
  J.Surface{+w, +h, +format, pixels} = s
  " i" ++ U32.show(w) ++ "," ++ U32.show(h) ++ "," ++ U32.show(format) ++ "," ++ hex.bytes(J.Surface.raw(~&1, J.Surface{w, h, format, pixels}))

def glyph.image(image: J.GlyphImage) -> String:
  match image:
    case J.GlyphEmpty{_, _}: " i-"
    case J.GlyphPixels{s}: image.out(s)

def glyph.size.surface(s: J.Surface) -> String:
  J.Surface{w, h, _, _} = s
  "," ++ sint(w) ++ "," ++ sint(h)

def glyph.size(image: J.GlyphImage) -> String:
  match image:
    case J.GlyphEmpty{w, h}: "," ++ sint(w) ++ "," ++ sint(h)
    case J.GlyphPixels{s}: glyph.size.surface(s)

def glyph.data.surface(s: J.Surface) -> String:
  J.Surface{+w, +h, +format, pixels} = s
  U32.show(w) ++ "," ++ U32.show(h) ++ "," ++ hex.bytes(J.Surface.raw(~&1, J.Surface{w, h, format, pixels}))

def glyph.data.image(image: J.GlyphImage) -> String:
  match image:
    case J.GlyphEmpty{w, h}: sint(w) ++ "," ++ sint(h) ++ ",-"
    case J.GlyphPixels{s}: glyph.data.surface(s)

def glyph.data(g: J.GlyphInfo) -> String:
  J.GlyphInfo{value, ox, oy, adv, image} = g
  " " ++ sint(value) ++ "," ++ sint(ox) ++ "," ++ sint(oy) ++ "," ++ sint(adv) ++ "," ++ glyph.data.image(image)

def glyphs.data(gs: List<J.GlyphInfo>) -> String:
  match gs:
    case Nil{}: ""
    case Con{g, rest}: glyph.data(g) ++ glyphs.data(rest)

def glyphs.count.cons(g: J.GlyphInfo, r: List<J.GlyphInfo> & U32) -> List<J.GlyphInfo> & U32:
  (gs, +n) = r
  (Con{g, gs}, (n + 1 : U32))

def glyphs.count(gs: List<J.GlyphInfo>) -> List<J.GlyphInfo> & U32:
  match gs:
    case Nil{}: (Nil{}, 0)
    case Con{g, rest}: glyphs.count.cons(g, glyphs.count(rest))

def data.counted(r: List<J.GlyphInfo> & U32) -> String:
  (gs, +n) = r
  " D" ++ U32.show(n) ++ glyphs.data(gs)

def data.out(d: J.Font.Data) -> String:
  match d:
    case J.FontDataNull{}: " D-"
    case J.FontDataRefused{}: " R"
    case J.FontDataGlyphs{gs}: data.counted(glyphs.count(gs))

def recs.out(rs: +List<J.Rectangle>) -> String:
  match rs:
    case Nil{}: ""
    case Con{+r, rest}:
      J.Rectangle{x, y, w, h} = r
      fbits(x) ++ "," ++ fbits(y) ++ "," ++ fbits(w) ++ "," ++ fbits(h) ++ ";" ++ recs.out(rest)

def atlas.made(a: Maybe<(J.Surface & +List<J.Rectangle>)>) -> String:
  match a:
    case None{}: " R"
    case Some{Tuple{s, rs}}: image.out(s) ++ " r" ++ recs.out(rs)

def atlas.out(r: List<J.GlyphInfo> & Maybe<(J.Surface & +List<J.Rectangle>)>) -> String:
  (_, a) = r
  atlas.made(a)

# Synthetic GRAYSCALE glyphs (w, h, seed): byte k is (k*2654435761 + seed*40503) >> 13.
def synth.bytes(n: Nat, +k: U32, +seed: U32) -> +List<U32>:
  match n:
    case 0n: Nil{}
    case 1n+r: Con{(((k * 2654435761 + seed * 40503 : U32) >> 13n) .&. 255 : U32), synth.bytes(r, (k + 1 : U32), seed)}

def synth.made(+w: U32, +h: U32, s: Maybe<J.Surface>) -> J.GlyphImage:
  match s:
    case None{}: J.GlyphEmpty{w, h}
    case Some{surface}: J.GlyphPixels{surface}

def synth.image(+w: U32, +h: U32, +seed: U32) -> J.GlyphImage:
  synth.made(w, h, Bool.pick(Maybe<J.Surface>, U32.is_eq((w * h : U32), 0), None{}, J.Surface.from_bytes(w, h, 1, synth.bytes(U32.to_nat((w * h : U32)), 0, seed))))

def synth.glyphs(+specs: +List<U32>, +i: U32) -> List<J.GlyphInfo>:
  match specs:
    case Con{+w, Con{+h, Con{+seed, rest}}}: Con{J.GlyphInfo{(32 + i : U32), 0, 0, 0, synth.image(w, h, seed)}, synth.glyphs(rest, (i + 1 : U32))}
    case _: Nil{}

type FontOp is Data:
  FInfo{}
  FTable{}
  FGlyph{cp: U32}
  FMeasure{text: +List<U32>, size: F32, spacing: F32}
  FTextEx{text: +List<U32>, x: F32, y: F32, size: F32, spacing: F32, tint: U32}
  FImageTextEx{text: +List<U32>, size: F32, spacing: F32, tint: U32}
  FCode{name: String}

type Op is Data:
  OBegin{}
  OEnd{}
  OClear{color: U32}
  OData{path: String, size: U32, cps: +List<U32>, count: U32, kind: U32}
  OAtlasData{path: String, size: U32, cps: +List<U32>, count: U32, kind: U32, acount: U32, asize: U32, pad: U32, method: U32}
  OAtlasSynth{specs: +List<U32>, acount: U32, asize: U32, pad: U32, method: U32}
  OMem{slot: U32, path: String, ext: String, size: U32, cps: +List<U32>, count: U32}
  OEx{slot: U32, path: String, size: U32, cps: +List<U32>, count: U32}
  OLoad{slot: U32, path: String}
  OUnload{slot: U32}
  ORefused{}
  OFont{slot: U32, call: FontOp}

type St is Type:
  St{frame: J.Frame, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>}

type St.Rest is Type:
  St.Rest{f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>}
'''

NEW_BEND = '''def atlas.of(+count: U32, +size: U32, +pad: U32, +method: U32, d: J.Font.Data) -> String:
  match d:
    case J.FontDataNull{}: " R"
    case J.FontDataRefused{}: " R"
    case J.FontDataGlyphs{gs}: atlas.out(J.Font.gen_image_atlas_for(libm(), gs, count, size, pad, method))

def info.text(+valid: Bool, info: J.FontInfo) -> String:
  J.FontInfo{base, count, padding, texture} = info
  " f" ++ sint(base) ++ "," ++ sint(count) ++ "," ++ sint(padding) ++ "," ++ U32.show(texture) ++ "," ++ Bool.pick(String, valid, "1", "0")

def info.with(+valid: Bool, r: J.Font & J.FontInfo) -> (J.Font & String):
  (font, info) = r
  (font, info.text(valid, info))

def info.font(r: J.Font & Bool) -> (J.Font & String):
  (font, +valid) = r
  info.with(valid, J.Font.info(font))

def glyph.row(+value: U32, +ox: U32, +oy: U32, +adv: U32, +rec: J.Rectangle, image: String) -> String:
  J.Rectangle{x, y, w, h} = rec
  "," ++ sint(value) ++ "," ++ sint(ox) ++ "," ++ sint(oy) ++ "," ++ sint(adv) ++ "," ++ fbits(x) ++ "," ++ fbits(y) ++ "," ++ fbits(w) ++ "," ++ fbits(h) ++ image

def table.extracted(r: J.Surface & Maybe<J.Surface>) -> J.Surface & String:
  match r:
    case Tuple{atlas, None{}}: (atlas, " i-")
    case Tuple{atlas, Some{s}}: (atlas, image.out(s))

def table.extract(+blank: Bool, atlas: J.Surface, +rec: J.Rectangle) -> J.Surface & String:
  match blank:
    case True{}: (atlas, " i-")
    case False{}: table.extracted(J.Surface.extract(atlas, rec))

def table.glyph(+g: FontCore.Glyph, r: J.Surface & String) -> J.Surface & String:
  (atlas, image) = r
  (atlas, " " ++ glyph.row(FontCore.Glyph.value(g), FontCore.Glyph.offset_x(g), FontCore.Glyph.offset_y(g), FontCore.Glyph.advance_x(g), J.Font.glyph.rec(g), image))

def table.go(glyphs: +List<FontCore.Glyph>, acc: +List<String>, r: J.Surface & String) -> J.Surface & +List<String>:
  match glyphs r:
    case Nil{} Tuple{atlas, text}: (atlas, Con{text, acc})
    case Con{+g, rest} Tuple{atlas, text}: table.go(rest, Con{text, acc}, table.glyph(g, table.extract(J.Font.glyph.blank(g), atlas, J.Font.glyph.rec(g))))

def table.done(+base: U32, +padding: U32, +glyphs: +List<FontCore.Glyph>, texture: J.Texture, r: J.Surface & +List<String>) -> J.Font & String:
  (atlas, texts) = r
  (J.Font{base, padding, glyphs, texture, atlas}, " T" ++ String.concat(List.reverse(&2, String, texts)))

def table(font: J.Font) -> J.Font & String:
  J.Font{+base, +padding, +glyphs, texture, atlas} = font
  table.done(base, padding, glyphs, texture, table.go(glyphs, Nil{}, (atlas, "")))

def glyph.image.surface(s: J.Surface) -> String:
  J.Surface{+w, +h, +format, pixels} = s
  image.out(J.Surface{w, h, format, pixels}) ++ "," ++ U32.show(w) ++ "," ++ U32.show(h)

def glyph.image.both(image: J.GlyphImage) -> String:
  match image:
    case J.GlyphEmpty{w, h}: " i-," ++ sint(w) ++ "," ++ sint(h)
    case J.GlyphPixels{s}: glyph.image.surface(s)

def glyph.info.some(+index: U32, +rec: J.Rectangle, g: J.GlyphInfo) -> String:
  J.GlyphInfo{value, ox, oy, adv, image} = g
  " g" ++ U32.show(index) ++ glyph.row(value, ox, oy, adv, rec, glyph.image.both(image))

def glyph.info(+index: U32, +rec: J.Rectangle, info: Maybe<J.GlyphInfo>) -> String:
  match info:
    case None{}: " g" ++ U32.show(index) ++ ",-"
    case Some{g}: glyph.info.some(index, rec, g)

def glyph.rec(+index: U32, info: Maybe<J.GlyphInfo>, r: J.Font & J.Rectangle) -> J.Font & String:
  (font, +rec) = r
  (font, glyph.info(index, rec, info))

def glyph.got(+cp: U32, +index: U32, r: J.Font & Maybe<J.GlyphInfo>) -> J.Font & String:
  (font, info) = r
  glyph.rec(index, info, J.Font.glyph_atlas_rec(font, cp))

def glyph.indexed(+cp: U32, r: J.Font & U32) -> J.Font & String:
  (font, +index) = r
  glyph.got(cp, index, J.Font.glyph_info(font, cp))

def vec(r: J.Font & M.Vector2) -> J.Font & String:
  (font, v) = r
  M.Vector2{x, y} = v
  (font, " v" ++ fbits(x) ++ "," ++ fbits(y))

def drawn(r: J.Frame & J.Font) -> (J.Frame & J.Font) & String:
  (r, "")

def keep(frame: J.Frame, r: J.Font & String) -> (J.Frame & J.Font) & String:
  (font, text) = r
  ((frame, font), text)

def image.maybe(s: Maybe<J.Surface>) -> String:
  match s:
    case None{}: " i-"
    case Some{surface}: image.out(surface)

def image.font(frame: J.Frame, r: J.Font & Maybe<J.Surface>) -> (J.Frame & J.Font) & String:
  (font, image) = r
  ((frame, font), image.maybe(image))

def code.text(t: Maybe<String>) -> String:
  match t:
    case None{}: " R"
    case Some{s}: " X" ++ hex.text(s)

def code.out(frame: J.Frame, r: J.Font & Maybe<String>) -> (J.Frame & J.Font) & String:
  (font, t) = r
  ((frame, font), code.text(t))

def fontop(call: FontOp, frame: J.Frame, font: J.Font) -> (J.Frame & J.Font) & String:
  match call:
    case FInfo{}: keep(frame, info.font(J.Font.is_valid(font)))
    case FTable{}: keep(frame, table(font))
    case FGlyph{+cp}: keep(frame, glyph.indexed(cp, J.Font.glyph_index(font, cp)))
    case FMeasure{text, size, spacing}: keep(frame, vec(J.Font.measure_text_ex(font, TC.string(text), size, spacing)))
    case FTextEx{text, x, y, size, spacing, tint}: drawn(J.Draw.text_ex(frame, font, TC.string(text), M.Vector2{x, y}, size, spacing, tint))
    case FImageTextEx{text, size, spacing, tint}: image.font(frame, J.Font.image_text_ex(font, TC.string(text), size, spacing, tint))
    case FCode{name}: code.out(frame, J.Font.as_code(font, CODES ++ "/" ++ name))

def slot.pair(text: String, pair: J.Frame & J.Font) -> (J.Frame & Maybe<J.Font>) & String:
  (frame, font) = pair
  ((frame, Some{font}), text)

def slot.some(r: (J.Frame & J.Font) & String) -> (J.Frame & Maybe<J.Font>) & String:
  (pair, text) = r
  slot.pair(text, pair)

# An empty slot is raylib's empty Font: its fields are 0.
def slot.empty(call: FontOp) -> String:
  match call:
    case FInfo{}: " f0,0,0,0,0"
    case _: " -"

def slot.run(frame: J.Frame, font: Maybe<J.Font>, call: FontOp) -> (J.Frame & Maybe<J.Font>) & String:
  match font:
    case None{}: ((frame, None{}), slot.empty(call))
    case Some{f}: slot.some(fontop(call, frame, f))

def St.put.at(slot: U32, text: String, frame: J.Frame, font: Maybe<J.Font>, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>) -> St:
  match slot:
    case 0: St{frame, font, f1, Con{text, log}}
    case _: St{frame, f0, font, Con{text, log}}

def St.put.pair(slot: U32, text: String, pair: J.Frame & Maybe<J.Font>, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>) -> St:
  (frame, font) = pair
  St.put.at(slot, text, frame, font, f0, f1, log)

def St.put(slot: U32, r: (J.Frame & Maybe<J.Font>) & String, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>) -> St:
  (pair, text) = r
  St.put.pair(slot, text, pair, f0, f1, log)

def St.font.at(slot: U32, frame: J.Frame, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>, call: FontOp) -> St:
  match slot:
    case 0: St.put(0, slot.run(frame, f0, call), None{}, f1, log)
    case _: St.put(1, slot.run(frame, f1, call), f0, None{}, log)

def St.font(s: St, +slot: U32, call: FontOp) -> St:
  St{frame, f0, f1, log} = s
  St.font.at(slot, frame, f0, f1, log, call)

def unload.one(frame: J.Frame, font: Maybe<J.Font>) -> (J.Frame & Maybe<J.Font>) & String:
  match font:
    case None{}: ((frame, None{}), "")
    case Some{f}: ((J.Font.unload(frame, f), None{}), "")

def St.unload.at(slot: U32, frame: J.Frame, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>) -> St:
  match slot:
    case 0: St.put(0, unload.one(frame, f0), None{}, f1, log)
    case _: St.put(1, unload.one(frame, f1), f0, None{}, log)

def St.unload(s: St, +slot: U32) -> St:
  St{frame, f0, f1, log} = s
  St.unload.at(slot, frame, f0, f1, log)

# A loaded font replaces the slot's (raylib overwrites f[slot] without
# unloading); refused loads print R.
def loaded.text(r: J.Frame & Maybe<J.Font>) -> (J.Frame & Maybe<J.Font>) & String:
  match r:
    case Tuple{frame, None{}}: ((frame, None{}), " R")
    case Tuple{frame, Some{font}}: ((frame, Some{font}), " L")

# raylib's empty Font (a file that does not load) logs as fields 0.
def loaded.io(r: J.Frame & Result<&1, &1, J.Surface.IOError, Maybe<J.Font>>) -> (J.Frame & Maybe<J.Font>) & String:
  match r:
    case Tuple{frame, Fail{_}}: ((frame, None{}), " L")
    case Tuple{frame, Done{font}}: loaded.text((frame, font))

def St.mem.at(slot: U32, frame: J.Frame, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>, ext: String, bytes: +List<U32>, +size: U32, +cps: +List<U32>, +count: U32) -> St:
  match slot:
    case 0: St.put(0, loaded.text(J.Font.load_from_memory(frame, ext, bytes, size, cps, count)), None{}, f1, log)
    case _: St.put(1, loaded.text(J.Font.load_from_memory(frame, ext, bytes, size, cps, count)), f0, None{}, log)

def St.mem.bytes(slot: U32, frame: J.Frame, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>, ext: String, +size: U32, +cps: +List<U32>, +count: U32, loaded: Result<&1, &1, J.Surface.IOError, +List<U32>>) -> St:
  match loaded:
    case Fail{_}: St{frame, f0, f1, Con{" no-file", log}}
    case Done{bytes}: St.mem.at(slot, frame, f0, f1, log, ext, bytes, size, cps, count)

def St.mem(s: St, +slot: U32, ext: String, +size: U32, +cps: +List<U32>, +count: U32, loaded: Result<&1, &1, J.Surface.IOError, +List<U32>>) -> St:
  St{frame, f0, f1, log} = s
  St.mem.bytes(slot, frame, f0, f1, log, ext, size, cps, count, loaded)

def St.io.slot(slot: U32, r: (J.Frame & Maybe<J.Font>) & String, f0: Maybe<J.Font>, f1: Maybe<J.Font>, log: +List<String>) -> St:
  match slot:
    case 0: St.put(0, r, None{}, f1, log)
    case _: St.put(1, r, f0, None{}, log)

def St.io(slot: U32, rest: St.Rest, r: J.Frame & Result<&1, &1, J.Surface.IOError, Maybe<J.Font>>) -> St:
  St.Rest{f0, f1, log} = rest
  St.io.slot(slot, loaded.io(r), f0, f1, log)

def St.frame.take(s: St) -> J.Frame & St.Rest:
  St{frame, f0, f1, log} = s
  (frame, St.Rest{f0, f1, log})

def St.note(s: St, text: String) -> St:
  St{frame, f0, f1, log} = s
  St{frame, f0, f1, Con{text, log}}

def St.frame(s: St, f: J.Frame -> J.Frame) -> St:
  St{frame, f0, f1, log} = s
  St{f(frame), f0, f1, log}

def step.data.text(+op: Op, +bytes: +List<U32>) -> String:
  match op:
    case OData{_, +size, +cps, +count, +kind}: data.out(J.Font.load_data(bytes, size, cps, count, kind))
    case OAtlasData{_, +size, +cps, +count, +kind, +acount, +asize, +pad, +method}: atlas.of(acount, asize, pad, method, J.Font.load_data(bytes, size, cps, count, kind))
    case _: ""

def step.loaded.data(s: St, +op: Op, loaded: Result<&1, &1, J.Surface.IOError, +List<U32>>) -> St:
  match loaded:
    case Fail{_}: St.note(s, " no-file")
    case Done{bytes}: St.note(s, step.data.text(op, bytes))

def step.io.frame(slot: U32, r: J.Frame & St.Rest, load: J.Frame -> IO(J.Frame & Result<&1, &1, J.Surface.IOError, Maybe<J.Font>>)) -> IO(St):
  (frame, rest) = r
  IO.bind(J.Frame & Result<&1, &1, J.Surface.IOError, Maybe<J.Font>>, St, load(frame), got => IO.pure(St, St.io(slot, rest, got)))

def step(op: Op, s: St) -> IO(St):
  match op:
    case OBegin{}: IO.pure(St, St.frame(s, f => J.Frame.begin_drawing(f)))
    case OEnd{}: IO.pure(St, St.frame(s, f => J.Frame.end_drawing(f)))
    case OClear{+color}: IO.pure(St, St.frame(s, f => J.Frame.clear_background(f, color)))
    case ORefused{}: IO.pure(St, St.note(s, " R"))
    case OData{path, +size, +cps, +count, +kind}:
      IO.bind(Result<&1, &1, J.Surface.IOError, +List<U32>>, St, J.Files.load_data(path), r => IO.pure(St, step.loaded.data(s, OData{"", size, cps, count, kind}, r)))
    case OAtlasData{path, +size, +cps, +count, +kind, +acount, +asize, +pad, +method}:
      IO.bind(Result<&1, &1, J.Surface.IOError, +List<U32>>, St, J.Files.load_data(path),
        r => IO.pure(St, step.loaded.data(s, OAtlasData{"", size, cps, count, kind, acount, asize, pad, method}, r)))
    case OAtlasSynth{+specs, +acount, +asize, +pad, +method}: IO.pure(St, St.note(s, atlas.out(J.Font.gen_image_atlas_for(libm(), synth.glyphs(specs, 0), acount, asize, pad, method))))
    case OMem{+slot, path, ext, +size, +cps, +count}:
      IO.bind(Result<&1, &1, J.Surface.IOError, +List<U32>>, St, J.Files.load_data(path), r => IO.pure(St, St.mem(s, slot, ext, size, cps, count, r)))
    case OEx{+slot, path, +size, +cps, +count}: step.io.frame(slot, St.frame.take(s), f => J.Font.load_ex(f, path, size, cps, count))
    case OLoad{+slot, path}: step.io.frame(slot, St.frame.take(s), f => J.Font.load(f, path))
    case OUnload{+slot}: IO.pure(St, St.unload(s, slot))
    case OFont{+slot, call}: IO.pure(St, St.font(s, slot, call))

def exec(ops: +List<Op>, s: St) -> IO(St):
  match ops:
    case Nil{}: IO.pure(St, s)
    case Con{op, rest}: IO.bind(St, St, step(op, s), s2 => exec(rest, s2))

def scene.finish(r: J.Frame & Maybe<J.Surface>, log: +List<String>) -> String:
  (_, surface) = r
  "S" ++ String.concat(List.reverse(&2, String, log)) ++ " F " ++ hex.maybe(surface)

def St.finish(s: St) -> String:
  St{frame, _, _, log} = s
  scene.finish(J.Frame.framebuffer(frame), log)

def St.run(ops: +List<Op>, frame: Maybe<J.Frame>) -> IO(Unit):
  match frame:
    case None{}: IO.print("no frame")
    case Some{f}: IO.bind(St, Unit, exec(ops, St{f, None{}, None{}, Nil{}}), s => IO.print(St.finish(s)))
'''

def bstr(text):
    return json.dumps(text)

def blist(values):
    return '[' + ', '.join(str(v & 0xFFFFFFFF) for v in values) + ']' if values else 'Nil{}'

def b_op(op):
    if declared(op):
        return 'ORefused{}'
    name, a = op[0], op[1:]
    calls = {
        'begin': lambda: 'OBegin{}', 'end': lambda: 'OEnd{}', 'clear': lambda: f'OClear{{{a[0]}}}',
        'data': lambda: f'OData{{{bstr(a[0])}, {a[1] & 0xFFFFFFFF}, {blist(a[2])}, {a[3] & 0xFFFFFFFF}, {a[4]}}}',
        'atlas_data': lambda: f'OAtlasData{{{bstr(a[0])}, {a[1]}, {blist(a[2])}, {a[3]}, {a[4]}, {a[5]}, {a[6]}, {a[7]}, {a[8]}}}',
        'atlas_synth': lambda: f'OAtlasSynth{{{blist([v for s in a[0] for v in s])}, {a[1]}, {a[2]}, {a[3]}, {a[4]}}}',
        'mem': lambda: f'OMem{{{a[0]}, {bstr(a[1])}, {bstr(a[2])}, {a[3]}, {blist(a[4])}, {a[5] & 0xFFFFFFFF}}}',
        'ex': lambda: f'OEx{{{a[0]}, {bstr(a[1])}, {a[2]}, {blist(a[3])}, {a[4] & 0xFFFFFFFF}}}',
        'load': lambda: f'OLoad{{{a[0]}, {bstr(a[1])}}}',
        'unload': lambda: f'OUnload{{{a[0]}}}',
    }
    if name in calls:
        return calls[name]()
    fonts = {
        'info': lambda: 'FInfo{}', 'table': lambda: 'FTable{}', 'glyph': lambda: f'FGlyph{{{a[1]}}}',
        'measure': lambda: f'FMeasure{{{blist(a[1])}, {bf(a[2])}, {bf(a[3])}}}',
        'text_ex': lambda: f'FTextEx{{{blist(a[1])}, {bf(a[2])}, {bf(a[3])}, {bf(a[4])}, {bf(a[5])}, {a[6]}}}',
        'image_text_ex': lambda: f'FImageTextEx{{{blist(a[1])}, {bf(a[2])}, {bf(a[3])}, {a[4]}}}',
        'code': lambda: f'FCode{{{bstr(a[1])}}}',
    }
    return f'OFont{{{a[0]}, {fonts[name]()}}}'

def b_scene(index, scene):
    return f'def scene.{index}() -> +List<Op>:\n  [' + ',\n    '.join(b_op(op) for op in scene['ops']) + ']'

def render(libm, codes):
    def build(selected, gpu):
        body = [PROGRAM, f'def libm() -> M.Libm:\n  M.{libm}{{}}', NEW_BEND.replace('CODES', bstr(codes))]
        prints = []
        for index, item in selected:
            body.append(b_scene(index, item))
            prints.append(f'    St.run(scene.{index}(), J.Frame.init_window({item["width"]}, {item["height"]}))')
        body.append('def main() -> IO(Unit):\n  do IO<Unit>:\n' + '\n'.join(prints) + '\n')
        return '\n\n'.join(body)
    return build

def main():
    args = probekit.arguments(__doc__)
    probe = probekit.Probe('ttf', args, raylib_options=fp.OPTIONS)
    libm = gradient_reference()
    fused = fp.fused_instructions(probe.library)
    if any(fused.values()):
        raise ProbeFailure(f'ttf: the reference build contains fused multiply-adds: {fused}')
    logf_control(probe)
    paths = font_files(probe.work, args.raylib_source)
    codes = probe.work / 'codes'
    codes.mkdir(exist_ok=True)
    items = scenes(paths, libm)
    expected = native_rows(probe, items, str(codes))
    actions = list(enumerate(items))
    lanes = probe.candidates(render(libm, str(codes)), actions, batch=12, parse=lambda text, selected: [line for line in text.splitlines() if line.strip()])
    probe.compare(expected, lanes, describe=lambda i: f'scene {items[i]["id"]}')
    probe.finish(scenes=len(items), operations=sum(len(s['ops']) for s in items), refused_operations=sum(declared(op) for s in items for op in s['ops']),
                 libm=libm, fused_free_objects=len(fused), scenes_sha256=hashlib.sha256(json.dumps(items, default=repr).encode()).hexdigest())

if __name__ == '__main__':
    main()
